### ISSUE TITLE
Server raises BadStatusLine after multiple multipart-encoded requests (since #3478)

### ISSUE THREAD

**Issue by keysmashes** [aio-libs/aiohttp#3968] opened 2019-08-08 10:00 UTC
## Long story short

I just upgraded aiohttp from 3.3.2 to 3.5.4, and the tests for my project started failing like this:

```pytb
$ python -m unittest discover test
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

I bisected the issue to commit 312cedb0a0ce8929f23f8c399b212bc1d9850d0b.

While bisecting, I got tracebacks like this as well, with what looks like fragments of the request header:

```pytb
Traceback (most recent call last):
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 274, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/http_parser.py", line 264, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/http_parser.py", line 427, in parse_message
    raise BadStatusLine(line) from None
aiohttp.http_exceptions.BadStatusLine: ost: 127.0.0.1:50095
```

The issue appears to happen when making multiple requests with a `data` attribute that contains a file-like object:

```python
await self.client.post(f"/ok", data={"f": BytesIO(b"123")})
```

even though this has worked fine previously and is [apparently](https://docs.aiohttp.org/en/stable/client_quickstart.html#post-a-multipart-encoded-file) the right way to send a multipart-encoded file.

## Expected behaviour

The server shouldn't raise strange exceptions when receiving multiple requests with a multipart-encoded file.

## Actual behaviour

It does.

## Steps to reproduce

- Install a recent version of aiohttp (that is, any version since 312cedb0a0ce8929f23f8c399b212bc1d9850d0b – 3.5.2 is the first release with this issue)
- Save the following test to a file and run it (`python -m unittest the_test.py`):

```python
from io import BytesIO

from aiohttp.test_utils import AioHTTPTestCase, unittest_run_loop
from aiohttp.web import Application, Response


async def ok(request) -> Response:
    return Response()


class MyTestCase(AioHTTPTestCase):
    async def get_application(self):
        app = Application()
        app.router.add_post("/ok", ok)
        return app

    @unittest_run_loop
    async def test_asyncio(self):
        print("doing request 1")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})
        self.assertEqual(resp.status, 200)

        print("doing request 2")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})
        self.assertEqual(resp.status, 200)
```

- Observe that you get output like this (the traceback changes slightly depending on which version you installed):

```pytb
$ python -m unittest test_aiohttp.py
doing request 1
doing request 2
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 274, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/http_parser.py", line 264, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/http_parser.py", line 427, in parse_message
    raise BadStatusLine(line) from None
aiohttp.http_exceptions.BadStatusLine: Accept: */*
F
======================================================================
FAIL: test_asyncio (test_aiohttp.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/deploy/backend/venv/lib/python3.7/site-packages/aiohttp/test_utils.py", line 478, in new_func
    func(self, *inner_args, **inner_kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/ubuntu/deploy/backend/test_aiohttp.py", line 25, in test_asyncio
    self.assertEqual(resp.status, 200)
AssertionError: 400 != 200

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (failures=1)
```

Removing the `BytesIO`, or the second request, stops the issue happening.

## Your environment

- Ubuntu 18.04
- aiohttp 3.5.4, or any version since 312cedb0a0ce8929f23f8c399b212bc1d9850d0b
- using aiohttp as both server and client (in unit test)

**Comment by MrCreosote** [comment] 2021-07-10 20:33
FWIW I just discovered this bug still exists on 3.7.4.post0 the hard way. Adding a `await request.release()` statement to the server function fixes the issue, but the documentation says user code should never call `release()`.

**Comment by Hanaasagi** [comment] 2021-07-13 17:47
Yes, `master` branch still exists this problem.

### Reproduce Code

```Python
# t.py
from io import BytesIO

from aiohttp.test_utils import AioHTTPTestCase
from aiohttp.web import Application, Response


async def ok(request) -> Response:
    return Response()


class MyTestCase(AioHTTPTestCase):
    async def get_application(self):
        app = Application()
        app.router.add_post("/ok", ok)
        return app

    async def test_asyncio(self):
        print("doing request 1")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})
        self.assertEqual(resp.status, 200)

        print("doing request 2")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})

```


### HTTP Messages

Run `strace -f -e trace=network -s 10000 python -m unittest t.py`. `7` is the client socket. `sendto` syscall shows the HTTP message payload.


```
sendto(7, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:39469\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=e1f40d8c929f4a8b8b2881efc5d73601\r\n\r\n", 232, 0, NULL, 0) = 232
sendto(7, "--e1f40d8c929f4a8b8b2881efc5d73601\r\n", 36, 0, NULL, 0) = 36
sendto(7, "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 117, 0, NULL, 0) = 117
strace: Process 1738010 attached
[pid 1737966] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1737966] recvfrom(8, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:39469\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=e1f40d8c929f4a8b8b2881efc5d73601\r\n\r\n--e1f40d8c929f4a8b8b2881efc5d73601\r\nContent-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 262144, 0, NULL, NULL) = 385
[pid 1737966] recvfrom(4, "\0", 4096, 0, NULL, NULL) = 1
[pid 1737966] recvfrom(4, 0x1a85f10, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1737966] sendto(7, "123", 3, 0, NULL, 0) = 3
[pid 1737966] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1737966] sendto(8, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nContent-Type: application/octet-stream\r\nDate: Tue, 13 Jul 2021 17:43:13 GMT\r\nServer: Python/3.9 aiohttp/4.0.0a1\r\n\r\n", 151, 0, NULL, 0) = 151
[pid 1737966] recvfrom(8, "123", 262144, 0, NULL, NULL) = 3
[pid 1737966] recvfrom(4, "\0", 4096, 0, NULL, NULL) = 1
[pid 1737966] recvfrom(4, 0x1a866c0, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1737966] recvfrom(7, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nContent-Type: application/octet-stream\r\nDate: Tue, 13 Jul 2021 17:43:13 GMT\r\nServer: Python/3.9 aiohttp/4.0.0a1\r\n\r\n", 262144, 0, NULL, NULL) = 151
[pid 1737966] sendto(5, "\0", 1, 0, NULL, 0) = 1
doing request 2
[pid 1737966] sendto(7, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:39469\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=605618e170e843f5ae37dc390da4a48b\r\n\r\n", 232, 0, NULL, 0) = 232
[pid 1737966] sendto(7, "--605618e170e843f5ae37dc390da4a48b\r\n", 36, 0, NULL, 0) = 36
[pid 1737966] sendto(7, "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 117, 0, NULL, 0) = 117
[pid 1737966] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1737966] recvfrom(4, "\0\0", 4096, 0, NULL, NULL) = 2
[pid 1737966] recvfrom(4, 0x1a89e30, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1737966] recvfrom(8, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:39469\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=605618e170e843f5ae37dc390da4a48b\r\n\r\n--605618e170e843f5ae37dc390da4a48b\r\nContent-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 262144, 0, NULL, NULL) = 385
[pid 1737966] sendto(7, "123", 3, 0, NULL, 0) = 3
[pid 1737966] sendto(5, "\0", 1, 0, NULL, 0) = 1
Error handling request
Traceback (most recent call last):
  File "/root/aiohttp/aiohttp/web_protocol.py", line 354, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

```

**Comment by Hanaasagi** [comment] 2021-07-13 18:22
Yes, this problem still exists on master branch.


### Reproduce Code

```Python
from io import BytesIO

from aiohttp.test_utils import AioHTTPTestCase
from aiohttp.web import Application, Response


async def ok(request) -> Response:
    return Response()


class MyTestCase(AioHTTPTestCase):
    async def get_application(self):
        app = Application()
        app.router.add_post("/ok", ok)
        return app

    async def test_asyncio(self):
        print("doing request 1")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})
        self.assertEqual(resp.status, 200)

        print("doing request 2")
        resp = await self.client.post(f"/ok", data={"f": BytesIO(b"123")})

```


### HTTP Message

Run `strace -f -e trace=network -s 10000 python -m unittest t.py` and get following `sendto` syscall. `7` is the client socket.


```
sendto(7, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:33737\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=491918eba8a84e2f8a7dbf90ff512d2e\r\n\r\n", 232, 0, NULL, 0) = 232
sendto(7, "--491918eba8a84e2f8a7dbf90ff512d2e\r\n", 36, 0, NULL, 0) = 36
sendto(7, "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 117, 0, NULL, 0) = 117
strace: Process 1846989 attached
[pid 1846931] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1846931] recvfrom(8, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:33737\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=491918eba8a84e2f8a7dbf90ff512d2e\r\n\r\n--491918eba8a84e2f8a7dbf90ff512d2e\r\nContent-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 262144, 0, NULL, NULL) = 385
[pid 1846931] recvfrom(4, "\0", 4096, 0, NULL, NULL) = 1
[pid 1846931] recvfrom(4, 0x1a00f10, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1846931] sendto(7, "123", 3, 0, NULL, 0) = 3
[pid 1846931] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1846931] sendto(8, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nContent-Type: application/octet-stream\r\nDate: Tue, 13 Jul 2021 18:17:23 GMT\r\nServer: Python/3.9 aiohttp/4.0.0a1\r\n\r\n", 151, 0, NULL, 0) = 151
[pid 1846931] recvfrom(8, "123", 262144, 0, NULL, NULL) = 3
[pid 1846931] recvfrom(4, "\0", 4096, 0, NULL, NULL) = 1
[pid 1846931] recvfrom(4, 0x1a016c0, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1846931] recvfrom(7, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nContent-Type: application/octet-stream\r\nDate: Tue, 13 Jul 2021 18:17:23 GMT\r\nServer: Python/3.9 aiohttp/4.0.0a1\r\n\r\n", 262144, 0, NULL, NULL) = 151
[pid 1846931] sendto(5, "\0", 1, 0, NULL, 0) = 1
doing request 2
[pid 1846931] sendto(7, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:33737\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=08268e2261d142b1a2f7f359827a6a56\r\n\r\n", 232, 0, NULL, 0) = 232
[pid 1846931] sendto(7, "--08268e2261d142b1a2f7f359827a6a56\r\n", 36, 0, NULL, 0) = 36
[pid 1846931] sendto(7, "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 117, 0, NULL, 0) = 117
[pid 1846931] sendto(5, "\0", 1, 0, NULL, 0) = 1
[pid 1846931] recvfrom(4, "\0\0", 4096, 0, NULL, NULL) = 2
[pid 1846931] recvfrom(4, 0x1a04e30, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 1846931] recvfrom(8, "POST /ok HTTP/1.1\r\nHost: 127.0.0.1:33737\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate, br\r\nUser-Agent: Python/3.9 aiohttp/4.0.0a1\r\nContent-Length: 196\r\nContent-Type: multipart/form-data; boundary=08268e2261d142b1a2f7f359827a6a56\r\n\r\n--08268e2261d142b1a2f7f359827a6a56\r\nContent-Type: application/octet-stream\r\nContent-Disposition: form-data; name=\"f\"; filename=\"f\"\r\nContent-Length: 3\r\n\r\n", 262144, 0, NULL, NULL) = 385
[pid 1846931] sendto(7, "123", 3, 0, NULL, 0) = 3
[pid 1846931] sendto(5, "\0", 1, 0, NULL, 0) = 1
Error handling request
Traceback (most recent call last):
  File "/root/aiohttp/aiohttp/web_protocol.py", line 354, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

```


But if I read the reqeust body, stops the issue happening. IMO, it looks like the buffer is not cleaned up, causing the request body and the next request to be processed together.

```Python
async def ok(request) -> Response:
    await request.read()  #
    return Response()

```

**Comment by Dreamsorcerer** [comment] 2024-08-16 18:58
Probably fixed by one of the recent multipart/parser fixes. Example tests here pass now.

**Closed as completed by Dreamsorcerer** 2024-08-16 18:58 UTC
