### ISSUE TITLE
Middlewares and nested applications

### ISSUE THREAD

**Issue by olexandr-klymenko** [aio-libs/aiohttp#2454] opened 2017-10-31 16:15 UTC
## Long story short

There is no clear notion about how middlewares should work in nested applications.
By common sense if middleware is mentioned in sub application it shouldn't be invoked for root application. But as the matter of fact it doesn't work the I expected. Every middleware is applied for every endpoint which is a bit wierd.

## Expected behaviour

middlewares used for declare sub application shouldn't be invoked when root application enpoint is requested

## Actual behaviour

every middleware is applied for every ebdpoint

## Steps to reproduce

1. Create root application
2. Create route in root application
3. Create sub app with middlewares
4. Attach sub app to root application
5. Request root application endpoint

## Your environment

python 3.6.3, aiohttp 2.3.1

**Comment by asvetlov** [comment] 2017-10-31 17:07
Middlewares are nested too.
If endpoints is handled by subapp -- middlewares from main app will be applied first, than subapp middlewares.

**Comment by olexandr-klymenko** [comment] 2017-10-31 17:39
I mean this is true the other way around as well. A middleware from sub app
affects on root application

**Comment by asvetlov** [comment] 2017-10-31 19:04
Hmm. If it's true -- this is a regression and behavior should be fixed.

**Comment by asvetlov** [comment] 2017-11-25 10:18
Steps to reproduce:

A sub application is not working and it is not very convenient.

```python


from aiohttp import web

async def index(request):
    print('*'*8, request.path, '*'*8)
    print('Index!')
    return web.Response(body=b'Index', content_type='text/plain')


async def login(request):
    print('*' * 8, request.path, '*' * 8)
    print('Login!')
    return web.Response(body=b'Login', content_type='text/plain')

async def cabinet(request):
    print('*' * 8, request.path, '*' * 8)
    print('Cabinet!')
    return web.Response(body=b'Cabinet', content_type='text/plain')


@web.middleware
async def auth_middleware(request, handler):
    print('m' * 8, request.path, 'm' * 8)
    print('Auth middleware!')
    return await handler(request)


root_app = web.Application()
admin_app = web.Application(
    middlewares=[auth_middleware],
)
admin_login_app = web.Application()

root_app.router.add_get('/', index, name='index')
admin_app.router.add_get('/cabinet/', cabinet, name='admin:cabinet')
admin_login_app.router.add_route('*', '/', login, name='login')

admin_app.add_subapp('/login', admin_login_app)
root_app.add_subapp('/admin/', admin_app)


web.run_app(root_app)

```

```bash
$ python server.py 
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
******** / ********
Index!
mmmmmmmm /admin/login/ mmmmmmmm
Auth middleware!
******** /admin/login/ ********
Login!
mmmmmmmm /admin/cabinet/ mmmmmmmm
Auth middleware!
******** /admin/cabinet/ ********
Cabinet!
```

**Comment by asvetlov** [comment] 2018-01-17 09:42
The issue is wrong.
There are two subapplications:
1. For handling /admin/* requests
2. Nested app for handling /admin/cabinet/

Obviously /admin/cabinet/ request is passed to subapp 1 (with its middlweares) and after that to nested subapp 2.

Everything is working as expected.

**Closed as completed by asvetlov** 2018-01-17 09:42 UTC
Labels: invalid, outdated
