### ISSUE TITLE
Brotli support not indicated by client through Accept-Encoding header

### ISSUE THREAD

**Issue by rgeronimi** [aio-libs/aiohttp#5219] opened 2020-11-11 17:18 UTC
🐞 **Describe the bug**
The aiohttp client does not send "br" in the "Accept-Encoding" header when brotli is enabled on the system

💡 **To Reproduce**
Install brotlipy
Make an aiohttp request to a server, logging the request headers. The Accept-Encoding header will indicate support for gzip and deflate but not br (brotli).

💡 **Expected behavior**
Brotli, when it is enabled, shall benefit from the same level of automatic support than gzip or deflate.

📋 **Your version of the Python**
3.7.8

📋 **Your version of the aiohttp/yarl/multidict distributions**
```console
Name: aiohttp
Version: 3.7.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages
Requires: attrs, yarl, multidict, async-timeout, chardet, typing-extensions
Required-by: slackclient, gcsfs
```
```console
Name: multidict
Version: 5.0.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages
Requires: 
Required-by: yarl, sanic, aiohttp
```
```console
Name: yarl
Version: 1.6.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

📋 **Additional context**
MacOS 10.15.7

**Comment by asvetlov** [comment] 2020-11-11 23:16
Makes sense.
Please feel free to make a pull request.

**Comment by derlih** [comment] 2020-11-12 07:25
@asvetlov I would say that this is a feature, not a bug.

**Comment by WisdomPill** [comment] 2020-11-23 13:41
Closing the issue since the PR has already been merged

**Closed as completed by WisdomPill** 2020-11-23 13:41 UTC
Labels: enhancement, need pull request
