### ISSUE TITLE
Applying backpressure to over-eager pipelining clients

### ISSUE THREAD

**Issue by njsmith** [aio-libs/aiohttp#1368] opened 2016-11-05 01:44 UTC
## Long story short

Asyncio seems to continue reading and buffering incoming requests from a client, even while it's still handling the previous request. This is weird and a mild DoS problem, since a client can trivially cause aiohttp's receive buffer to grow to unbounded size.

## Expected behaviour

If I try to send lots of requests at an aiohttp server then it should buffer a small amount and then apply backpressure to me.

## Actual behaviour

It just queues up requests indefinitely.

## Steps to reproduce

Point this client at an aiohttp server:

```python
import sys, socket
host, port = sys.argv[1], int(sys.argv[2])
with socket.create_connection((host, port)) as sock:
    get = b"GET / HTTP/1.1\r\nHost: " + host.encode("ascii") + b"\r\n\r\n"
    requests_sent = 0
    while True:
        sock.sendall(get)
        requests_sent += 1
        if requests_sent % 1000 == 0:
            print("Sent {} requests", requests_sent)
```

Ideally after some time the number of requests sent should stop increasing because `sock.sendall` starts blocking, and the aiohttp server's memory usage should stop increasing.

**Comment by fafhrd91** [comment] 2016-11-05 01:58
I am planing to work on this task

**Comment by pfreixes** [comment] 2017-06-08 10:47
any news about that?

**Comment by fafhrd91** [comment] 2017-06-08 15:27
we need champion for this issue. fix is relatively simple.

**Comment by zmedico** [comment] 2017-06-08 16:49
Some useful configuration parameters:
* Individual POST size limits.
* Cumulative concurrent POST size limits.
* Concurrent connection limits. Allow the kernel to queue new connections and eventually refuse them when it grows too large (kernel queue size controlled by net.core.somaxconn sysctl on Linux). 
* For the connections that have been accepted, limit accepting new connections from the same client address, with separate limits to trigger queuing or rejecting of new connections from the same client address.
* Limit the combined number of concurrently accepted connections from all clients.

**Comment by fafhrd91** [comment] 2017-06-08 16:57
first two points are implemented on aiohttp.web level, other points are not related to this issue. 
this one is about one client sending too much pipelined http requests

**Comment by asvetlov** [comment] 2018-02-27 19:20
We are going to make every write an async function.
#2698

**Comment by fafhrd91** [comment] 2018-02-27 19:26
we just need to limit number of in-flight requests

**Comment by asvetlov** [comment] 2020-01-03 13:44
The issue is fixed in aiohttp 3.x line.
Sorry for keeping it open for a long time

**Closed as completed by asvetlov** 2020-01-03 13:44 UTC
