### ISSUE TITLE
Problem with updating aiohttp

### ISSUE THREAD

**Issue by XCanG** [aio-libs/aiohttp#1885] opened 2017-05-12 22:16 UTC
## Long story short

Can't update aiohttp by pip command:

```
C:\Windows\system32>pip install -U aiohttp
Collecting aiohttp
  Using cached aiohttp-2.0.7.tar.gz
Requirement already up-to-date: chardet in c:\python\python36\lib\site-packages (from aiohttp)
Requirement already up-to-date: multidict>=2.1.4 in c:\python\python36\lib\site-packages (from aiohttp)
Requirement already up-to-date: async_timeout>=1.2.0 in c:\python\python36\lib\site-packages (from aiohttp)
Requirement already up-to-date: yarl<0.11,>=0.10.0 in c:\python\python36\lib\site-packages (from aiohttp)
Installing collected packages: aiohttp
  Found existing installation: aiohttp 2.0.2
    Uninstalling aiohttp-2.0.2:
      Successfully uninstalled aiohttp-2.0.2
  Running setup.py install for aiohttp ... error
  Rolling back uninstall of aiohttp
Exception:
Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 34: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 34: invalid continuation byte
```

## My environment

python 3.6.1 x64 on Windows 10 x64

**Comment by fafhrd91** [comment] 2017-05-12 22:20
this is similar to aio-libs/yarl#60

this is has something to do with locale. could you try to install aiohttp from master?
same for yarl package?

**Comment by AraHaan** [comment] 2017-05-13 02:53
Also why is it not trying to download from the wheels? Try to manually download the wheels to python 3.6 to take care of the issue.

Mind giving me what ``python`` on the command line gives if python 3.6 is in your path. This is so I know if it is 32 or 64 bit python.

Also if you would like I can build an 32 bit wheel for 3.6 and an 64 bit one as well to manually upload to pypi if need to be since I just now noticed windows wheels for 3.6 seems nonexistant for some reason.

**Comment by AraHaan** [comment] 2017-05-13 07:35
Alright made the wheels to aiohttp, multidict, and yarl. They are present here. https://github.com/AraHaan/wheels Also note that I may or may not update these all the time.

I assume you know how to manually download the wheels you need and install in this order ``multidict`` -> ``yarl`` -> ``aiohttp``.

Let me know if these wheels fix your issue.

**Comment by XCanG** [comment] 2017-05-14 16:11
Hm, I starting manually upgraded packages, first two are normally upgraded, but on aiohttp it stucked with error:
```
C:\wheels-master>python -m pip install C:/wheels-master/aiohttp-2.0.7-cp36-cp36m-win_amd64.whl
Processing c:\wheels-master\aiohttp-2.0.7-cp36-cp36m-win_amd64.whl
Requirement already satisfied: yarl<0.11,>=0.10.0 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: async-timeout>=1.2.0 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: chardet in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: multidict>=2.1.4 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Installing collected packages: aiohttp
Exception:
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python\Python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Python\Python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Python\Python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Python\Python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python\Python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Python\Python36\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Python\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Python\\Python36\\Lib\\site-packages\\aiohttp\\_http_parser.cp36-win_amd64.pyd'
```
I check permission but it not changed for other folders... Then I rename that file and run command again and get similar issue:
```
Exception:
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python\Python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Python\Python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Python\Python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Python\Python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python\Python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Python\Python36\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Python\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Python\\Python36\\Lib\\site-packages\\aiohttp\\_websocket.cp36-win_amd64.pyd'
```
After renaming that file again it finish installation.

```
C:\wheels-master>python -m pip install C:/wheels-master/aiohttp-2.0.7-cp36-cp36m-win_amd64.whl
Processing c:\wheels-master\aiohttp-2.0.7-cp36-cp36m-win_amd64.whl
Requirement already satisfied: yarl<0.11,>=0.10.0 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: async-timeout>=1.2.0 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: multidict>=2.1.4 in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Requirement already satisfied: chardet in c:\python\python36\lib\site-packages (from aiohttp==2.0.7)
Installing collected packages: aiohttp
Successfully installed aiohttp-2.0.7
```

Looks like something happen with that 2 files...

**Comment by AraHaan** [comment] 2017-05-14 17:39
Nice to see the wheels helped fix the issue. I manually compiled the latest commit on the python 3.6 branch just to be able to install all I needed to make that 64 bit wheel. And good thing I did as 32 bit computers have became obsolete since after like 2010.

I am going to start patching pip yet again today that if that decode fails with that error anymore that it will return s unchanged as a fallback. At least as an temporary fix.

**Comment by asvetlov** [comment] 2017-05-14 17:55
I've added Windows Python 3.6 wheels for multidict yesterday.
Wheels for aiohttp itself will be updated on new release (coming soon).
yarl is good already.
Regarding to permission problem: I pretty sure the issue is with local @XCanG Windows box. Wheel doesn't contain permission flags at all.

Let's close the issue.

**Closed as completed by asvetlov** 2017-05-14 17:55 UTC
Labels: outdated

**Comment by asvetlov** [comment] 2017-05-14 17:58
P.S. 
`pip uninstall aiohttp` with cleaning up `'C:\\Python\\Python36\\Lib\\site-packages\\aiohttp'` folder might help.
Maybe some virus protection software blocks DLL updating, I not sure.

**Comment by XCanG** [comment] 2017-05-14 18:08
I have no any antiviruses, so it not that.

**Comment by AraHaan** [comment] 2017-05-14 18:19
Well it is because of this actually https://github.com/pypa/pip/pull/4310 it has nothing to deal with yarl or aiohttp this whole time. As I originally suspected on the yarl issue above.

**Comment by asvetlov** [comment] 2017-05-14 18:38
@AraHaan maybe you are right.
I don't use Windows for long time and not aware about issues with installing python packages.
I hope the problem is already solved by `pip`
