### ISSUE TITLE
aiohttp.ClientSession(json_serialize=orjson.dumps).post(json={}) error: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by un-human** [aio-libs/aiohttp#5975] opened 2021-08-30 02:08 UTC
### Describe the bug

aiohttp.ClientSession(json_serialize=orjson.dumps).post(json={'xxx':'xxx'})
orjson.dumps is bytes, and  aiohttp/payload.py  JsonPayload super().__init__( dumps(value).encode(encoding),)  AttributeError: 'bytes' object has no attribute 'encode'

### To Reproduce

aiohttp.ClientSession(json_serialize=orjson.dumps).post(url='',json={'xxx':'xxx'})

### Expected behavior

aiohttp/payload.py  
JsonPayload super().__init__( 
    dumps(value).encode(encoding) if not isinstance(value,bytes) else value
)

### Logs/tracebacks

```python-traceback
File "D:\develop\python37\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "D:\develop\python37\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
AttributeError: 'bytes' object has no attribute 'encode'
```

### Python Version

```console
$ python --version
3.7.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: d:\develop\python37\lib\site-packages
Requires: multidict, yarl, attrs, typing-extensions, chardet, async-timeout
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: d:\develop\python37\lib\site-packages
Requires:
Required-by: yarl, sanic, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: d:\develop\python37\lib\site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

### OS

windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by greshilov** [comment] 2021-10-01 23:54
It's not a bug. `orjson.dumps` by default returns `bytes` in opposite to `str` returned by a standard library `json.dumps`.
It's clearly stated in the `orjson` docs:
> To migrate from the standard library, the largest difference is that orjson.dumps returns bytes and json.dumps returns a str. 

`aiohttp.ClientSession` expects that object passed with `json_serialize` kwarg is a function, that replicates standard library behavior. You can easily fix it in your code by doing something like:

```
orjson_wrapped = lambda data: orjson.dumps(data).decode()
async with aiohttp.ClientSession(json_serialize=orjson_wrapped) as session:
    await session.post("https://google.com", json={'xxx': 'xxx'})
```

The problem is, `orjson` developers changed the return type from `str` to `bytes` on purpose. They wanted to increase the performance, and the wrapper above will affect it.

@Dreamsorcerer I think we can close this issue, since it's not a bug, but rather a wrong library usage.

**Comment by Dreamsorcerer** [comment] 2021-10-02 12:55
Right, I suspect that extra code to handle bytes would decrease performance for others, so the wrapper that @greshilov demonstrated seems like the best solution for the moment.

**Closed as completed by Dreamsorcerer** 2021-10-02 12:55 UTC
Labels: bug
