### ISSUE TITLE
`pip install` requires `--no-build-isolation`

### ISSUE THREAD

**Issue by blueyed** [aio-libs/aiohttp#3704] opened 2019-04-19 09:57 UTC
Trying to install aiohttp from the Git repo results in:
```
% pip install -e .
…
  Getting requirements to build wheel ... error
  Complete output from command /home/daniel/.pyenv/versions/tmp-system-aiohttp-n3RpAV/bin/python /home/daniel/.pyenv/versions/tmp-system-aiohttp-n3RpAV/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp23d44iu3:
  Install cython when building from git clone
  Hint:
    pip install cython

  ----------------------------------------
Command "/home/daniel/.pyenv/versions/tmp-system-aiohttp-n3RpAV/bin/python /home/daniel/.pyenv/versions/tmp-system-aiohttp-n3RpAV/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp23d44iu3" failed with error code 1 in /home/daniel/Vcs/aiohttp
```

However `cython` is installed already, and this is caused by pip using a special mode since there is a `pyproject.toml` file.  `pip install --no-build-isolation -e .` works.

See https://github.com/pypa/pip/issues/5416#issuecomment-406788181.

**Comment by asvetlov** [comment] 2019-04-19 10:12
Thanks for the report.
@webknjaz and I are trying to find now a quick fix but long-term solution.
Please stay tuned.

**Comment by webknjaz** [comment] 2019-04-19 10:14
Duplicate of #3581

**Closed as completed by webknjaz** 2019-04-19 10:14 UTC
Labels: outdated

**Comment by blueyed** [comment] 2019-04-19 11:56
Thanks for working on this already.

Given that https://github.com/aio-libs/aiohttp/issues/3581 is quite involved and might take some more time you might want to consider just not using `pyproject.toml` for now - pip triggers this behavior just because the file is there, and you are only using it for `[tool.towncrier]`.

A trivial fix is the following.  But I can see that this might not work in general, and something like https://github.com/aio-libs/aiohttp/pull/3589 is needed.

```diff
diff --git a/pyproject.toml b/pyproject.toml
index e666dfc1..bc9a22ad 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -5,3 +5,6 @@ directory = "CHANGES/"
 title_format = "{version} ({project_date})"
 template = "CHANGES/.TEMPLATE.rst"
 issue_format = "`#{issue} <https://github.com/aio-libs/aiohttp/issues/{issue}>`_"
+
+[build-system]
+requires = ["setuptools>=40.8.0", "wheel", "cython"]
```

**Comment by webknjaz** [comment] 2019-04-19 12:00
@blueyed yes, we're considering temporary removal of `pyproject.toml` and your solution suggests that the end-users must have a build toolkit (gcc and libs) because otherwise `cython` install will fail.
In our case, we need it to be optional which is quite tricky.

I hope to have some kind of solution today anyway. I think that currently, we should just recommend `--no-build-isolation` for dev env and discourage any uses or `-e` in non-dev envs.
