### ISSUE TITLE
Unable to catch exception. socket.gaierror Name or service not known

### ISSUE THREAD

**Issue by jwest75674** [aio-libs/aiohttp#4321] opened 2019-11-04 19:34 UTC
## Long story short

Hello,

I am trying to make many http requests for a research project I am working on, where in I am working against a large historical list of domain names. Part of this information gathering stage has to do with determining what percentage of these old websites are simply no longer alive.
aiohttp appears to (correctly) throw an exception when requested to GET from a domain that no longer resolves, however, it appears that there isn't a way to catch the exception. (My apologies if I am simply too novice to have spotted a workaround)

Cleaned up pseudo code:
```python
from aiomultiprocess import Pool
import aiohttp
import asyncio
(etc...)

async def async_request(domain_url_list):
    async with Pool(settings.concurrent_processes) as pool:
        request_timer = await pool.map(get, domain_url_list)
    return request_timer

async def get(domain_url):
    try:
        async with aiohttp.request("GET", url, headers=headers) as response:
            ##Process Request
    except Exception as err:
        logging.error('EXCEPTION DETECTED: {} '.format(err)
        handle_exception(err)
        
async def main():
    filepath = '/path/to/file/filename.csv'
    domain_url_list = []
    with open(filepath) as file:
        for line in file:
            domain_url_list.append(line.stip())
    get_timers = await async_request(allurls)
    print('Single Get Average Runtime: {}'.format(sum(working_time)/len(get_timers)))


if __name__ == '__main__':
    asyncio.run(main())

```
## Expected behaviour

I would hope to be able to catch any aiohttp request exceptions either with a setting to ignore them, or a normal try catch loop as I had used initially, however the exception appears to bypass them?

## Actual behaviour
```python-traceback
Traceback (most recent call last):
  File "getgrequestsdellaio.py", line 350, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "getgrequestsdellaio.py", line 326, in main
    get_timers = await async_request(allurls)
  File "getgrequestsdellaio.py", line 165, in async_request
    request_timer = await pool.map(get, domain_url_list)
  File "/home/josh/.local/lib/python3.7/site-packages/aiomultiprocess/core.py", line 434, in map
    return await self.results(tids)
  File "/home/josh/.local/lib/python3.7/site-packages/aiomultiprocess/core.py", line 398, in results
    raise ProxyException(tb)
aiomultiprocess.core.ProxyException: Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "uvloop/loop.pyx", line 1430, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "getgrequestsdellaio.py", line 92, in get
    async with aiohttp.request("GET", url, headers=headers) as response:
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/client.py", line 1051, in __aenter__
    self._resp = await self._coro
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/josh/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host deaddomain.net:80 ssl:default [Name or service not known]
```
## Steps to reproduce

Use normally, but GET a dead domain. No bypass.

## Your environment

python 3.7, fresh (pip) install of all libraries and modules in the last week or so.
Debian 10

## Other notes
I tried using aiohttp sessions, but could not manage to get it working with the map() based multiprocessing solution. The aiomultiprocessing library recommends the aiohttp.request("GET"... Setup, which is why it is used.

**Comment by webknjaz** [comment] 2019-11-04 20:12
The example is incomplete and uses third-party libs (`uvloop`, `aiomultiprocess`). For this to be aiohttp issue you have to provide a reproducible example that only uses `asyncio` and `aiohttp`.

**Comment by hh-h** [comment] 2019-11-05 10:39
try run this example, it works fine
```python
import asyncio

import aiohttp


async def main():
    try:
        async with aiohttp.request("GET", "deaddomain.net:80") as resp:
            print(resp)
    except Exception as exc:
        print(f"EXCEPTION {exc}")


asyncio.run(main())
```

**Comment by webknjaz** [comment] 2019-11-05 14:52
Closing because it seems to be an error in a third-party lib.

**Closed as completed by webknjaz** 2019-11-05 14:52 UTC
Labels: invalid

**Comment by jwest75674** [comment] 2019-11-05 15:30
Thanks guys, My apologies for the trouble!
