### ISSUE TITLE
Reconnect on request timeout defaults to ssl = None

### ISSUE THREAD

**Issue by T-Woodward** [aio-libs/aiohttp#3785] opened 2019-05-21 09:55 UTC
## Long story short

The problem I'm having is that when a request times out my session will attempt to reconnect. But on this re-connection attempt by default it appears to assume that the host website is not SSL encrypted. The connection attempt then fails and the thread dies which significantly complicates graceful handling of these errors.

## Expected behaviour

Initial connections work fine, I would expect re-connection attempts to work similarly well. 

## Actual behaviour
File "C:/Users/teddy/Documents/BITMEX Trading System/BITMEX_MA_V3.py", line 1699, in amend_order
    async with session.put('https://www.bitmex.com/api/v1/order',headers=headers,data=msg) as resp:
  File "C:\Users\teddy\Anaconda3\envs\untitled1\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Users\teddy\Anaconda3\envs\untitled1\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "C:\Users\teddy\Anaconda3\envs\untitled1\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\teddy\Anaconda3\envs\untitled1\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "C:\Users\teddy\Anaconda3\envs\untitled1\lib\site-packages\aiohttp\connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.bitmex.com:443 ssl:None [getaddrinfo failed]

## Steps to reproduce

session=aiohttp.ClientSession()
async with session.post('https://XXXX',headers=headers,data=msg) as resp:

## Your environment

 Client

**Comment by asvetlov** [comment] 2019-05-22 07:01
I use aiohttp to work with HTTPS servers a lot, basically every day.
Never seen a problem mentioned by you.
Maybe your re-connection logic is buggy?

*Steps to reproduce* chapter is incomplete.
Please make a code that I can execute on my laptop to see your error.

**Comment by T-Woodward** [comment] 2019-05-22 14:53
Ah I'm not sure I really can reproduce it in an isolated and concise manner. You would need a host that is otherwise valid to neglect to respond to a request once already connected. I'm not sure how to create such a thing. If you know of a way for me to reproduce this situation, please tell me. But just on speculation I thought my proposed explanation may have been the issue given the 'ssl:None' flag in the exception. Also, I looked at the source code and as far as I can tell it does look like the ssl setting defaults to None in the methods that this timeout triggered.

**Comment by asvetlov** [comment] 2019-05-23 09:00
In this context `ssl:None` means that you didn't provide `ssl.SSLContext` object for the request, default ssl client context is used.

**Comment by asvetlov** [comment] 2019-10-03 20:07
Fixed on master, now the exception looks like `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.bitmex.com:443 ssl:default [getaddrinfo failed]`

**Closed as completed by asvetlov** 2019-10-03 20:07 UTC
