### ISSUE TITLE
Unable to install dev requirements

### ISSUE THREAD

**Issue by modelmat** [aio-libs/aiohttp#3584] opened 2019-01-29 07:19 UTC
## Long story short
For some reason I am unable to install the dev requirements, as the `pip install -e .` command executed by them fails with this code:
```py
if (here / '.git').exists() and not USE_CYTHON:
    print("Install cython when building from git clone", file=sys.stderr)
    print("Hint:", file=sys.stderr)
    print("  pip install cython", file=sys.stderr)
    sys.exit(1)
```
Yet, opening the python terminal and typing `from Cython.Build import cythonize` works just fine, and `pip freeze` shows `Cython==0.29.2`. This makes me unable to run any tests. Commenting out these lines results in a fully working pip install & `make test`.

## Expected behaviour

Installs fine.

## Actual behaviour
I receive this error.
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command "/home/modelmat/Documents/GitHub Projects/aiohttp/venv/bin/python3" "/home/modelmat/Documents/GitHub Projects/aiohttp/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py" get_requires_for_build_wheel /tmp/tmpqx4ffm0k:
  Install cython when building from git clone
  Hint:
    pip install cython
```

## Steps to reproduce
Follow the exact steps as shown in CONTRIBUTING.md.

## Your environment
aiohttp: `c145bd8416b1edb11214254e07013f92d91b6537`
uname -a: `Linux desktop 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux`

**Comment by kxepal** [comment] 2019-01-29 07:58
@Modelmat 
Are you're using pip==19 to catch this issue? There is a similar issue with it: https://github.com/aio-libs/aiohttp/issues/3581

**Comment by modelmat** [comment] 2019-01-29 08:09
Yes. Should I close this issue then?

**Comment by webknjaz** [comment] 2019-01-29 08:12
Duplicate of #3581

**Closed as completed by webknjaz** 2019-01-29 08:12 UTC
Labels: bug, outdated
