### ISSUE TITLE
False-positive deprecation warning for partial async handlers

### ISSUE THREAD

**Issue by nicktimko** [aio-libs/aiohttp#3252] opened 2018-09-07 20:36 UTC
## Long story short

Wrapping a coroutine function with a `functools.partial` causes a DeprecationWarning to trigger.

## Steps to reproduce
Something like
```
def private_route(handler):
    return functools.partial(handler, private=True)

async def hello(request, private: bool):
    return web.Response(text='boo' if private else 'hello')

handler = private_route(hello)
app.router.add_route('get', '/hello', handler)  # DepWarning
```

causes [a `DeprecationWarning`](https://github.com/aio-libs/aiohttp/blob/558519adae70795ab5c99e150e0ac10e80f68d36/aiohttp/web_urldispatcher.py#L113-L114) to be hit.

I think when called as `handler(req)` will immediately run through the partial and return the coroutine, which can then be awaited. It seems like the dep warning in this case is more of a false-positive. Maybe an expression like the ending one below could suppress it? If this is indeed just a false-positive and I'm the only ~complainer~ reporter, I could live.

```
import functools
import inspect

async def f():
    pass

fp = functools.partial(f)

inspect.iscoroutinefunction(f)  # True
inspect.iscoroutinefunction(fp) # False
isinstance(fp, functools.partial) and inspect.iscoroutinefunction(fp.func) # True
```

Tweak?:

```diff
         if asyncio.iscoroutinefunction(handler):
             pass
         elif inspect.isgeneratorfunction(handler):
             warnings.warn("Bare generators are deprecated, "
                           "use @coroutine wrapper", DeprecationWarning)
+        elif (isinstance(handler, functools.partial) and
+              asyncio.iscoroutinefunction(handler.func)):
+            pass
         elif (isinstance(handler, type) and
               issubclass(handler, AbstractView)):
             pass
         else:
             warnings.warn("Bare functions are deprecated, "
                           "use async ones", DeprecationWarning)
```

## Your environment

I'm using aiohttp 3.3.2 on Python 3.6.5 on Ubuntu 16.04, but it looks like master would still trigger the warning.

**Comment by webknjaz** [comment] 2018-09-08 06:42
Feel free to send a PR

**Comment by asvetlov** [comment] 2018-09-08 11:04
The issue is essentially the same as https://github.com/aio-libs/aiohttp/issues/1993#issuecomment-419431628
I doubt if introspection errors should be fixed on aiohttp level.

**Closed as completed** 2018-09-26 21:51 UTC
Labels: wontfix, outdated

**Comment by nicktimko** [comment] 2018-09-27 14:50
I guess I'm curious if my read was correct though: when synchronous handler support is removed, would this synchronous coroutine-handler-generator still work fine?

**Comment by asvetlov** [comment] 2018-09-27 14:52
Are you asking for `functools.partial`?
No, partials registration will raise an exception
