### ISSUE TITLE
Registered functors raise a bare func deprecation warning

### ISSUE THREAD

**Issue by vmarkovtsev** [aio-libs/aiohttp#4519] opened 2020-01-20 10:49 UTC
## Long story short

Class instance with `async def __call__` triggers DeprecationWarning: Bare functions are deprecated. This is different from #3252 where `functools.partial` generates a sync `def __call__`. 

## Steps to reproduce

```python
class AsyncPartial:
    def __init__(self, arg):
        self.arg = arg

    async def __call__(self, request):
        return do_smth_with(request, self.arg)

app.router.add_get("/xxx", AsyncPartial(42))  # DeprecationWarning
app.router.add_get("/xxx", AsyncPartial(42).__call__)  # No warning, ugly
```

## Your environment

Python 3.7.5
aiohttp 3.6.2

**Comment by asvetlov** [comment] 2020-01-24 16:16
Sorry, the problem is out of aiohttp scope.
`asyncio.iscoroutinefunction()` (or `ispect.iscoroutinefunction()`) should be fixed.
See also https://bugs.python.org/issue38225 discussion

**Closed as completed by asvetlov** 2020-01-24 16:16 UTC

**Comment by vmarkovtsev** [comment] 2020-01-25 07:11
@asvetlov when you are saying "out of scope", you really mean that I should file a dedicated bug report on bugs.python.org, correct?

**Comment by asvetlov** [comment] 2020-01-25 08:54
I think we need to make decision about mentioned issue, select the attribute name, and write a patch for cpython.
Nothing to do on aiohttp side

**Comment by vmarkovtsev** [comment] 2020-01-25 20:01
@asvetlov Sorry, I am not sure what you mean. aiohttp is irrelevant - this one I don't doubt and I understood at once :smile: 

What decision? Do you mean whether that is officially acknowledged on bugs.python.org? Which attribute, do you mean `__call__`? Why select the name? Do you mean adding another check in the `iscoroutinefunction()` implementation? :question: 

What shall I do in the end? Clone this issue to bugs.python.org? Submit a cpython patch for your consideration? Do nothing and you've got it covered?

**Comment by asvetlov** [comment] 2020-01-27 08:08
I mean something like the following *may* work eventually after making https://bugs.python.org/issue38225 done:
```
class A:
    async def __call__(self, *args):
        pass

    __call__.__async__ = True
```

I have no evidence if this feature will be implemented this way until a (not existing yet) pull request is landed.  The next step on moving the issue forward is making a tested prototype.  Caution, it can take longer and harder than you expect if you have no experience of hacking CPython.
