### ISSUE TITLE
Connector timeout includes time waiting for connector from pool

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#2648] opened 2018-01-09 21:16 UTC
## Long story short

Typically connector timeouts means time waiting for a connection to a server, and does not include any time waiting for a connection from the pool

This is because the timeout is started here: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L289

and in connect it will wait for a connector: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L382

## Expected behaviour

conn_timeout should only include active time waiting to connect to a server as this isn't an error and expected behavior.  I'd suggest moving the timeout to the connector. 

## Actual behaviour

If you make a large number of requests, and have limited number of connectors, your requests may timeout w/o even trying to connect to the server because no connectors are available.

## Steps to reproduce

create a large number of requests with a limited number of connectors with short conn_timeout.

## Your environment
Any platform with aiohttp 2.x

**Comment by pfreixes** [comment] 2018-01-10 07:29
I would prefer to keep having the protection of the timeout to cancel those connections that were waiting for to much time for a free slot. Indeed, all asyn operations that are behind the connect are susceptibles to be cancelled.

Said that, its true that having a generic exception can be missleading, the owner of a Aiohttp servive that is getting timeouts accesung to a an external service wont be able to understand the root cause of this timeouts, and in the worst case will be attributed to issues with the external service while the problem was the pool limitation.

My suggestion here is, lets keep the timeout feature but lets improve the API allowing the developer to make a diagnose of the issue.

**Comment by thehesiod** [comment] 2018-01-10 17:16
the problem is the meaning of connect timeout.  Connect timeout is supposed to mean a network timeout, not a process timeout.  If you want to have a high-level process timeout that would be the timeout parameter passed to the request method.  Further there's no way to implement a true network timeout with the current implementation w/o overriding private methods.

**Comment by pfreixes** [comment] 2018-01-10 21:53
You are right, I didn't notice that the whole execution was covered by the `read_timeout`. Then, I do agree with you that we would need to move this timeout context as much closer to the real connection. Also, taking into account that could be also interesting skip the DNS part.

This is an interesting subject, IMHO real network timeouts in Asyncio does not exist. The closest to a network timeout is that one that schedules a coroutine that won't have more than 1 asynchronous call nested. Otherwise, the cancel callback could cancel a future that might be still pending to be started, u other corner cases. This such situation usually happens when the reactor is saturated.

**Comment by thehesiod** [comment] 2018-01-10 21:58
ya, this whole subject is long standing gripe I have about aiohttp, resulting in lots of ugly hacks in aiobotocore.  aiohttp needs real network based connect and read timeouts.  IMO if someone wants an overarching one use that high-level timeout thingy, or just do it at the call-site as an overarching timeout makes too many assumptions due to task scheduling.

**Comment by wumpus** [comment] 2018-01-19 17:26
As a heavy user of the aiohttp client in a crawler, I am surprised to learn that the timeouts include the time waiting for a slot. I really want a network timeout, and not a slot-waiting timeout.

**Comment by pfreixes** [comment] 2018-01-20 10:09
what do you think @asvetlov? I believe that if everybody agrees we might have it for the next release.

**Comment by asvetlov** [comment] 2018-01-20 18:18
It's very complex question.
Depending on user expectation timeout meaning changes.
It can be grand total, network activity only, grand total without waiting for connection from pool -- you can invent a fourth definition, sure.

We definitely should change something but I don't see clean design yet.

**Comment by wumpus** [comment] 2018-06-17 03:10
This bug appears to have been fixed by #2768

**Comment by asvetlov** [comment] 2018-06-17 08:13
@wumpus thanks for a ping.
The issued is implemented, closing it.

**Closed as completed by asvetlov** 2018-06-17 08:13 UTC
Labels: outdated
