### ISSUE TITLE
Enable to remove "Content-Length: 0" for GET Request

### ISSUE THREAD

**Issue by ga0** [aio-libs/aiohttp#2167] opened 2017-08-04 03:40 UTC
## Long story short

When I send GET request to some http server with the  "Content-Length: 0" header, will cause a aiohttp.ServerDisconnectedError. If I remove this header, everything goes well.

I don't know why these server hate empty content-length header so much.

## Expected behaviour

Some args to remove Content-Length if it is 0 and method is GET.

## Steps to reproduce

You can test by using the comands below.

```
curl -v -H "Content-Length: 0" http://115.238.34.168

curl -v http://115.238.34.168 
```

## Your environment
aiohttp: 2.0.7

OS & Python: 
* macOS with Python 3.6.1
* CentOS7 with Python 3.4.5

**Comment by socketpair** [comment] 2017-08-04 05:15
https://stackoverflow.com/questions/978061/http-get-with-request-body?answertab=active#tab-top

Content length mean presensce of a body, but with zero length. I prefer to close as "not a bug". No one http-client will send such requests. And sending body with GET-request difinitely signify a bug in client. RFC on HTTP is not strict enough, so current implementation of this case still leaves aiohttp RFC-compliant. Handling such reqests will not bring any benefits, just code bloat. 

Why you want such functionality ?

Also please update aiohttp and re-test.

**Comment by ga0** [comment] 2017-08-11 02:48
* Why you want such functionality ?

Because I found send GET request with  "Content-Length: 0" header to  some kind of servers will cause a bad request error.

* Also please update aiohttp and re-test.

I have tried aiohttp-2.2.5, still a "Content-Length: 0" in the request's header.

**Comment by socketpair** [comment] 2017-08-11 04:40
Since it's not an security error, does not fix any real problem, does not add new functionality, I'm -3 for  this issue.

**Comment by fafhrd91** [comment] 2017-08-11 05:12
is it possible to disable `content-length` with `skip_auto_headers`?

**Comment by asvetlov** [comment] 2017-08-11 17:13
Unfortunately no.

**Comment by fafhrd91** [comment] 2017-08-11 17:49
I think we should support this use case

**Comment by asvetlov** [comment] 2017-08-11 18:06
Agree.
I see two options:
1. Respect `skip_auto_headers` in `Content-Length` and `Content-Encoding`
2. Implement #2019 and add a low level control for all HTTP request transformation details.

I prefer second bullet but it requires much more work.
Skipping mandatory fields like `Content-Length` in our prime API could make a mess (not 100% sure but I have bad guts feeling about this approach).

**Comment by socketpair** [comment] 2017-08-12 08:50
1. `skip_auto_headers` controls RESPONSE headers generation.
2. Topic started say us about `content-length` in REQUEST.
3. `Content-Length: 0` is not the same as missing conten-length. This is trictly written in RFC. And so we should not change anything regarding generation/suppressing of `Content-Length`.
4. RFC say us that http-server SHOULD ignore reuqest-body of GET-requests (not MUST).

Again, my opinion, that we should reject such request. Such requests are bugs in client implementation.

**Comment by socketpair** [comment] 2017-08-12 10:21
Sorry, I did not catch original problem :(. As I think, Aiohttp has a bug. GET/HEAD/TRACE-requests hould not send content-length in any case.

**Comment by socketpair** [comment] 2017-08-12 11:37
Please review https://github.com/aio-libs/aiohttp/pull/2191

**Comment by ga0** [comment] 2017-09-06 01:32
I appreciate that you value this issue. 👍
I have to ask when this issue will be solved, or merged into the master branch? Do you have a plan?

I apologize for my poor English.
Thank you all you guys!

**Comment by asvetlov** [comment] 2017-10-19 16:51
Fixed by #2167

**Closed as completed by asvetlov** 2017-10-19 16:51 UTC

**Comment by herono2010** [comment] 2019-09-05 09:31
add another header. "Connection:Keep-Alive"

**Comment by herono2010** [comment] 2019-09-05 09:32
"Connection:Keep-Alive" and "Content-Length:0" should be together.

**Comment by asvetlov** [comment] 2019-09-06 08:34
Why? 
Moreover, `Connection: keep-alive` is not required by HTTP/1.1 at all.
