### ISSUE TITLE
Request params do not encode right

### ISSUE THREAD

**Issue by habibutsu** [aio-libs/aiohttp#1901] opened 2017-05-17 19:51 UTC
```python
import asyncio 
import aiohttp

loop = asyncio.get_event_loop()

async def request():
    session = aiohttp.ClientSession(loop=loop)
    params = [('key', '1;2;3')]
    async with session.get('http://httpbin.org/get', params=params) as r:
        assert r.url == 'http://httpbin.org/get?key=1;2;3', r.url

loop.run_until_complete(request())

```
## Expected behaviour

No exception

## Actual behaviour
```python
AssertionError: http://httpbin.org/get?key=1&2=&3=
```
## Your environment

python 3.6.1
aiohttp 2.0.7
yarl 0.10.2

**Comment by fafhrd91** [comment] 2017-05-17 19:54
@asvetlov could you check, seems related to yarl

**Comment by Kilerd** [comment] 2017-05-18 02:16
i just changed your code like this:
```python
import asyncio 
import aiohttp

loop = asyncio.get_event_loop()

async def request():
    session = aiohttp.ClientSession(loop=loop)
    params = [('key', '1')]
    async with session.get('http://httpbin.org/get', params=params) as r:
        print(r.url)

        assert r.url == 'http://httpbin.org/get?key=1'

loop.run_until_complete(request())
```
but it assert that:
```
http://httpbin.org/get?key=1
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    loop.run_until_complete(request())
  File "\Python\Python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "test.py", line 12, in request
    assert r.url == 'http://httpbin.org/get?key=1'
AssertionError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0314B230>
```

i think that there is some bug on r.url
cuz in my opinion, `r.url` should be `str` type, but not `aiohttp.URL` instance instead.
that is the reason why it asserted: aiohttp.URL is not the same as str even if their content is same.

but the question is there is an `url_obj` in response.
i infer that, the between about `url` and `url_obj` is that the type of former should be str, and the other should be `aiohttp.URL`

apparently, there is a bug, or there is some other feature instead?

i also open a issue like yours in  https://github.com/aio-libs/aiohttp/issues/1898, but there is no response.

**Comment by Kilerd** [comment] 2017-05-18 02:21
yep, i got it.
```python
from yarl import URL
```
then, 
```python
assert r.url == URL('http://httpbin.org/get?key=1')
```

but it does not look pretty.

there is, i hope and i think, another way to do like that.

**Comment by asvetlov** [comment] 2017-05-18 11:04
On my way

**Comment by asvetlov** [comment] 2017-06-26 15:21
Well, the problem is a bit tricky.
Question is: how to process semicolon chars in query part?
This [StackOverflow question](https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator) is a good summary, especially the first answer.

Long story short: `;` char was used as a parameter separator for ages along with `&`. 
Python internally process both by `urllib.parse.parse_qsl` function.

Later in 2014 W3C recommendations `;` has gone, only `&` is supported. But `yarl` uses `parse_qsl` -- and works as expected (at least by me).

`aiohttp` cannot just append `params` to the end of url -- it should parse URL and extend it's query part with `params`. That's why we have query part transformation.

Sure, I could don't split query by `;` but not sure what existing code we will break -- looks like people still use old agreements.

Right now there are two workarounds: 

1. Don't use `params` at all and construct full URL with query parameters before passing it to `client.get()`.
2. Percent-encode `;` character (replace it with `'%3B'`) before sending as `params`.

@kxepal @fafhrd91 what do you suggest?

**Comment by asvetlov** [comment] 2017-06-26 15:31
Well, we could auto-escape all `&=;` in keys/values by `url.with_query()` and `url.update_query()` calls.
It doesn't make everybody happy but at least we;ll get consistent behavior.

**Comment by kxepal** [comment] 2017-06-26 15:48
I'm a bit don't follow how recommendations about `application/x-www-form-urlencoded` format relates to URL's query part handling.

**Comment by asvetlov** [comment] 2017-06-26 16:02
Technically URL's query part should be encoded as `application/x-www-form-urlencoded`

**Comment by andreip** [comment] 2017-07-28 09:24
Hi @asvetlov,

Adding to the example above, some related case I stumbled into since it's related.

```python
import asyncio 
import aiohttp

loop = asyncio.get_event_loop()

async def request():
    async with aiohttp.ClientSession(loop=loop) as session:
        params = [('url', 'https://example.com/a/b/1329285?_mc=RSS_IWK_EDT')]
        async with session.get('http://httpbin.org/get', params=params) as r:
            assert str(r.url) == 'http://httpbin.org/get?url=https%3A%2F%2Fexample.com%2Fa%2Fb%2F1329285%3F_mc%3DRSS_IWK_EDT', r.url

loop.run_until_complete(request())
```

but I get `AssertionError: http://httpbin.org/get?url=https://example.com/a/b/1329285?_mc%3DRSS_IWK_EDT`

But that technically isn't right, since the value of the `url` key from query string needs to be URL encoded with `quote_plus` for that to work. So I thought, ok, I'll encode it for you, so I made params be:

```python
params = [('url', 'https%3A%2F%2Fexample.com%2Fa%2Fb%2F1329285%3F_mc%3DRSS_IWK_EDT')]
```

but then I got the same assertion error as before,

`AssertionError: http://httpbin.org/get?url=https://example.com/a/b/1329285?_mc%3DRSS_IWK_EDT`.

So `aiohttp` seems to decode what I just encoded, but that's not the right behavior, this http request won't work properly. I'd like to be able to at least ask `aiohttp` to not touch the params. I tried sending a full URL already formatted with `url?k=encoded_value1&k2=encoded_value2...` without using `params` at all but it's the same behavior, my `encoded_value`s get decoded back and sent over the network. Also tried sending a string into `params` in the hope that that won't get decoded, but it was still decoded.

I'm trying to send some full path URLs to an API for enqueue and process and the URLs obviously need to be encoded.

Any easy way I can achieve what I'm after?

**Comment by pfreixes** [comment] 2017-08-26 14:48
In any case this is a change from older aiohttp versions, it has broken at least one of our micro services when we tried to upgrade to the last aiohttp 2.X. Any decision regarding this issue? Im more inclined on escape the ;

**Comment by asvetlov** [comment] 2017-10-01 11:27
Fixed by yarl==0.13.0

**Closed as completed by asvetlov** 2017-10-01 11:27 UTC
Labels: outdated

**Comment by samuelcolvin** [comment] 2017-10-01 11:29
I think @asvetlov might mean yarl==0.13.0

**Comment by asvetlov** [comment] 2017-10-01 11:30
@samuelcolvin sure, thanks.
Message is corrected.
