### ISSUE TITLE
SSL self signed certificate / Python 3.8.0b3

### ISSUE THREAD

**Issue by bcroston** [aio-libs/aiohttp#4009] opened 2019-08-27 22:58 UTC
## Long story short

Using a self-signed SSL certificate, it works with Python 3.7 but not Python 3.8.0b3.

## Expected behaviour

```$ wget --no-check-certificate https://localhost:8443```
index.html downloaded, containing 'Hello, World!'.

## Actual behaviour

```--2019-08-27 23:35:04--  https://localhost:8443/  
Resolving localhost (localhost)... ::1, 127.0.0.1  
Connecting to localhost (localhost)|::1|:8443... failed: Connection refused.  
Connecting to localhost (localhost)|127.0.0.1|:8443... connected.  
GnuTLS: The TLS connection was non-properly terminated.  
Unable to establish SSL connection.  
```

## Steps to reproduce

Create certificate:

```bash
$ openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
 -out sslcert.crt -keyout sslcert.key
```

Python code:

```python
import ssl
from aiohttp import web

async def handle(request):
    text = 'Hello world!'
    return web.Response(text=text)

if __name__ == '__main__':
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_context.check_hostname = False
    ssl_context.load_cert_chain('sslcert.crt','sslcert.key')
    app = web.Application()
    app.add_routes( [web.get('/',handle), ] )
    web.run_app(app, ssl_context=ssl_context)
```

## Your environment

Raspbian Buster / Debian Stretch
Python 3.8.0b3
aiohttp 3.5.4 (server)

**Comment by webknjaz** [comment] 2019-08-28 10:42
aiohttp doesn't do anything on top of standard TLS support from stdlib. So all the answers should be @ https://docs.python.org/3/library/ssl.html.

**Comment by webknjaz** [comment] 2019-08-28 10:46
Try `openssl s_client -connect localhost:8443` to see the TLS details. Also, are you sure your server is listening to this port? I don't see where you set this up.

**Comment by bcroston** [comment] 2019-08-29 11:42
> Try `openssl s_client -connect localhost:8443` to see the TLS details. Also, are you sure your server is listening to this port? I don't see where you set this up.

This is not returning a certificate when run under Python 3.8 but does under 3.7.
The port is the aiohttp default for https connections and is reported when you run the script.

I have since written a simple asyncio-based echo server that uses the same ssl certificate.  This works in both Python 3.7 and 3.8.

**Comment by bcroston** [comment] 2019-08-29 13:05
Output from `openssl s_client -connect localhost:8443`:
```CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1567083853
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by webknjaz** [comment] 2019-08-29 19:08
Have you tried to compare this with what `openssl s_client -connect localhost:8443` returns when you use Python 3.7?

**Comment by webknjaz** [comment] 2019-08-29 19:40
Alright. I was able to reproduce this locally.

###### Python 3.8.0b3+:
```console
$ curl -k -vvv https://127.0.0.1:8443
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file
```
```console
$ openssl s_client -connect localhost:8443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1567107548
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
###### Python 3.7
```console
$ curl -k -vvv https://127.0.0.1:8443
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* skipping SSL peer certificate verification
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: O=Internet Widgits Pty Ltd,ST=Some-State,C=AU
*       start date: Aug 29 19:20:29 2019 GMT
*       expire date: Aug 28 19:20:29 2020 GMT
*       common name: (nil)
*       issuer: O=Internet Widgits Pty Ltd,ST=Some-State,C=AU
> GET / HTTP/1.1
> Host: 127.0.0.1:8443
> User-Agent: curl/7.65.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 12
< Date: Thu, 29 Aug 2019 19:35:15 GMT
< Server: Python/3.7 aiohttp/3.5.4
< 
* Connection #0 to host 127.0.0.1 left intact
Hello world!%                                                                                                                           
```
```console
$ openssl s_client -connect localhost:8443
CONNECTED(00000003)
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify error:num=18:self signed certificate
verify return:1
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify return:1
---
Certificate chain
 0 s:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
   i:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFYDCCA0igAwIBAgIJAItNl4lyUOK9MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMTkwODI5MTkyMDI5WhcNMjAwODI4MTkyMDI5WjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAonGwjL6oOmmwVeIoCSpb0tgF2YtR5P9d5X0CErbkOUpn76WmDDNs6/op
x9zsZKVdDRN9TUEetSeFX3WuM8fkSpo/KigxmVilYmrX0DBw2Nd6GDrm0PdowGX2
TOepsT1eg65uWto0YQpcLWWQfnSk9exUSHiGrU5gsCAPckpboyDI4w75hILGmDE0
tsM+IHzvFJDerGLRUv/Tu3xBhdMX8tVvI3/O45CljEc94uU7tL2xREueSJ+kwzf7
HlRAR75wxGhEMjXERAuxouept4J3JbgJR2MpsJK2xRoTILqmzNLisj/lzhv4C17A
ofXg2iSr+4KMpcuufnZ3LmApzLjNLcRgAUBWzUW9HUpoywQI4B2A0uHFxbjIG05I
H2Nck9YDPoo1ymIQVl+SXFRhTXApdQdC+CWMg+WLUFhhxlTMn2aXMBORNn2TMB41
wtK1uvVs6wNKUIBSeCcd7W/0G+5GQkNC1yxzfkahpVJPDTkwsYZQTmFvJUejgpac
vnJxdi4n91CHrKlPTRtGQMBAlYLZNibYl5PALOYDqIabPdyxytnSOqMOPHmWXyBQ
HIE12c0Rw2+Nj2X6NUaZQmDyAuwwn0jpmK5/syaxz+qlyNJWgl+x2+DlLpnVXM+2
2EK3pBmjAOw2ee5R7Ne5VV3+13jWycMp9JT3X6324ZZEGO2VtI0CAwEAAaNTMFEw
HQYDVR0OBBYEFGxYsGp6J3ZRxr5fHI54Rl87yNXcMB8GA1UdIwQYMBaAFGxYsGp6
J3ZRxr5fHI54Rl87yNXcMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
ggIBAAARrY534KhcF6fjUSCvld4Uez082EDBjMpQywadrIG/bORVhn/t1jboi3re
WaS/kr5h47a82WGdZHQVy+6AGa6ROF27qM88HztQXEZ85l/R2Wlzs8/OsdmW1L8C
mkr4YiBy5l5lxNyrrmcU49RLpk2ozIzN8Syc73P8LeKVqtuIlHyz38ogGz9i30kS
WblDrsjZlrIaqk4w3+i0FZOtas0bTEa/z9oEzUIJKwOcx6wNIvSs/x5NRUBVCrno
foGWB7xW+qSNrdc/pxoQ6LEBa8/y/lN2u+zZvmzTpVXN93LVOSzJe5nvozEOtaIq
5Xs4qddQspmmOdm2USodGFb6T8B563Gz7HSKLTjvbTljqxi2h712CliIn2Wqpk/V
asZ1pgZk/5RvsCIizDq9aqZH3lwihEGWhWs7uxjwZ7UbWSx8TxSSd8VqB5KcSFd6
9rRCcWVPkQEzT+BsfV1h8xQX819tel1WgtsXoUUomrHopA7PDh8L7WBal1QvBCSU
UiLuAnouSiNFoL0KjWH6PC6+nvLvAphz60/iByTkT87XmropahC3EjLo7ICAv/lX
0nutmew/ddCqzJUe2Vnf2BNABsN6u2V/wv39gcP7TtDr12O/HvWqVcY8PP2yx7cP
qpWazzAlrzPWdsoe5btvKonG9dmXXZPJDfpR83MP0RVIcAFK
-----END CERTIFICATE-----
subject=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2261 bytes and written 269 bytes
Verification error: self signed certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 3F059E9C8E549C4D0532CA2A4F33F546FE03131860904B645AC8621D6B4DF8EE
    Session-ID-ctx: 
    Master-Key: CA709EDA37ADA28925E975D7A5AD53F91CF0A8FE14106F5359C6052D4EE0AA5A947AE0F3CB4D8DC948C218238AB44CD6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - b4 16 f0 00 4e 1c 1d b3-cb 58 2c ec c0 66 98 11   ....N....X,..f..
    0010 - 20 11 15 95 5b ee cc cf-e8 8a 75 3d 9e 2a 56 a8    ...[.....u=.*V.
    0020 - c9 3d 8a 10 27 dd 33 65-9d 31 d2 56 b2 35 26 29   .=..'.3e.1.V.5&)
    0030 - e8 a7 76 ca 67 34 86 f8-5b d0 78 1c bd 3c 29 94   ..v.g4..[.x..<).
    0040 - 84 6a 74 84 1a 04 29 0b-33 5d 25 e4 a9 0f 7b d9   .jt...).3]%...{.
    0050 - 46 f3 f4 08 59 2f 22 42-26 99 e9 0d 18 4d 63 f8   F...Y/"B&....Mc.
    0060 - 4e 22 ba 5b e1 22 6f 5a-0e a9 a2 64 34 00 25 91   N".[."oZ...d4.%.
    0070 - 27 14 44 db 2b ba 14 1d-ae 9e 21 1c 9e 4e 3d 54   '.D.+.....!..N=T
    0080 - a6 57 af b9 18 34 18 e7-84 64 74 70 bb f2 40 47   .W...4...dtp..@G
    0090 - 94 e0 48 ac ed 62 ec 94-b2 70 da d9 65 bc 8a 6c   ..H..b...p..e..l

    Start Time: 1567107463
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: yes
---
^C
```

**Comment by webknjaz** [comment] 2019-08-29 19:45
The issue reveals itself once you enable [asyncio debug mode]:
```python-traceback
$ PYTHONASYNCIODEBUG=1 ./tls_py38_4009.py
======== Running on https://0.0.0.0:8443 ========
(Press CTRL+C to quit)
Error on transport creation for incoming connection
handle_traceback: Handle created at (most recent call last):
  File "./tls_py38_4009.py", line 24, in <module>
    web.run_app(app, ssl_context=ssl_context)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/aiohttp/web.py", line 401, in run_app
    loop.run_until_complete(_run_app(app,
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/base_events.py", line 563, in run_forever
    self._run_once()
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/base_events.py", line 1836, in _run_once
    handle._run()
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/selector_events.py", line 189, in _accept_connection
    self.create_task(accept)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/base_events.py", line 427, in create_task
    task = tasks.Task(coro, loop=self, name=name)
Traceback (most recent call last):
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/asyncio/selector_events.py", line 198, in _accept_connection2
    protocol = protocol_factory()
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/aiohttp/web_server.py", line 57, in __call__
    return RequestHandler(self, loop=self._loop, **self._kwargs)
  File "~/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 136, in __init__
    self._keepalive = False
AttributeError: 'RequestHandler' object has no attribute '_keepalive'
^C%                                                                                                                                     
```

[asyncio debug mode]: https://docs.python.org/3/library/asyncio-dev.html#asyncio-debug-mode

**Comment by webknjaz** [comment] 2019-08-29 19:51
It looks like it's fixed in master.

**Comment by webknjaz** [comment] 2019-08-29 19:52
@asvetlov is the fix backported?

**Comment by asvetlov** [comment] 2019-09-27 15:48
Yes. aiohttp 3.6.1 should work fine

**Closed as completed by asvetlov** 2019-09-27 15:48 UTC
Labels: bug, server

**Comment by bcroston** [comment] 2019-09-28 17:21
Confirmed working for me.  Thanks for your great work on aiohttp!
