### ISSUE TITLE
Add a parameter to function `ClientSession._request`

### ISSUE THREAD

**Issue by liyu133** [aio-libs/aiohttp#5511] opened 2021-03-02 05:44 UTC
🐣 **Is your feature request related to a problem? Please describe.**

My request url is encoded, but the function is default with False, it been encoded once again,  so I get a bad response

💡 **Describe the solution you'd like**

I hope add a parameter to this function, it named `url_encoded`, default `False`,and make this file line 381 `url = URL(str_or_url, encoded=url_encoded)` 

❓ **Describe alternatives you've considered**

📋 **Additional context**

**Comment by webknjaz** [comment] 2021-03-06 21:55
This is by design. You can construct `yarl.URL` objects and pass them to the coroutine calls instead of strings. These won't be re-encoded.

**Comment by webknjaz** [comment] 2021-03-06 21:55
Duplicate of #5512.

**Closed as completed by webknjaz** 2021-03-06 21:55 UTC
Labels: enhancement
