### ISSUE TITLE
Big chunk decoding makes content.iter_any() iterate over partial content

### ISSUE THREAD

**Issue by Anvil** [aio-libs/aiohttp#1899] opened 2017-05-17 13:59 UTC
## Long story short

When receiving a very big chunk (response has `Transfer-Encoding: chunked.` header), result of `aiohttp.ClientSession().request(...).content.iter_any()` yields partial chunks.

## Expected behaviour

I would expect chunks integrity to be respected, and `iter_any()` to yield reasonably-decodable json content.

## Actual behaviour

`iter_any()` yields partial chunks, which is Bad(tm).

## Steps to reproduce

I think this basic code below is enough if you find a server that answers big chunks. We internally managed to reproduce the bug by querying a docker server with URL `GET /v1.24/containers/json?all=1 HTTP/1.1.`. Server would reply a very big 350 000 bytes long chunk, and instead of yielding that chunk iter_any() just served us an about-30k-bytes-long beginning of chunk.

```python
response = await aiohttp.ClientSession().request(...)
async for chunk in response.content.iter_any():
    json.loads(chunk)
```

If ValueError is raised, you lose the game.

## Your environment
Ubuntu Xenial (python 3.5.2) with aiohttp 2.0.7 (bug is reproducible on aiohttp master branch).

(update: updated code sample)

**Comment by Anvil** [comment] 2017-05-18 06:50
Forgot to mention, the bug can be triggered with and without exporting `AIOHTTP_NO_EXTENSIONS=1`.

**Comment by Anvil** [comment] 2017-05-19 07:33
A bit of clarification: this is not exactly about "big" chunks. It's more about "partially-received" chunks. 
See fa81efae007e0874eec0fa93ee6602047e6c7193: we receive partial data for whatever reason (maybe because the chunk is too big to fit in a few packets and maybe because network is slow - whatever), and aiohttp is nevertheless able to yield that partial content while the program expected consistent data.

**Comment by fafhrd91** [comment] 2017-05-19 15:28
I replied in PR

**Comment by pkch** [comment] 2017-06-02 19:31
@Anvil  Do you mind clarifying the original scenario? 

Specifically, you say that Docker API returns data in large chunks. Let's say `aiohttp` actually did `yield` the entire chunk at a time. It seems that, even then, your `json.loads(chunk)` can fail. 

IIUC, the entire response is a valid JSON, so if you split it in 2 or more chunks, each of then chunks is guaranteed to be invalid JSON (if you split a JSON object or a JSON array into more than 1 piece, the `{`, `[` won't match the closing `}`, `]`).

So again IIUC, your original code would only work correctly if Docker sent the entire content in a single chunk. But in that case, you might as well wait for the entire data to be received, there's no point iterating through chunks. 

(And in fact, Docker makes no guarantees that there's only 1 chunk sent, so you really should not iterate through chunks and attempt to `json.loads` each of them.)

**Comment by fafhrd91** [comment] 2017-06-02 19:34
seems some developers uses Transfer-Encoding as part of application protocol.

**Comment by pkch** [comment] 2017-06-02 20:00
@fafhrd91  I don't think so... AFAIU, the server here (Docker) does *not* hijack Transer-Encoding for any application level purposes. It follows all the design guidelines, in that it returns a *single* JSON object *at the end* (after all the chunks are assembled together). And, since Docker does not assign any significance at all to the underlying chunks, there seems to be no need to look at them from the application level.

So I'm really not sure why @Anvil found it necessary to look at each individual underlying chunk.

**Closed as completed** 2017-06-03 13:53 UTC
Labels: invalid, wontfix, outdated

**Comment by pkch** [comment] 2017-06-03 16:06
@asvetlov I recommend you close this not with `wontfix` but with `invalid` (or whatever label corresponds to a "not a bug").

@fafhrd91 (Clarifying my previous comment.) You may well be right that some developers use Transfer-Encoding as part of an application protocol. But even if they do use this horrible and unreliable hack, it would have to start with the server-side developers. Client-side developers can't just decide to rely on Transfer-Encoding if the server doesn't promise anything special about the chunks it sends, and breaks content into chunks at arbitrary boundaries.

My point was that Docker is certainly a well-behaved server. Perhaps @Anvil  only used Docker as an example, and if so, I'd be interested to know which real-world server they actually had trouble with.

BTW, all the libraries I've seen that parse multiple JSON objects obtained from chunked HTTP either [use state](https://github.com/jonnyreeves/chunked-request#writing-a-custom-chunk-parser) to work correctly, or [rely on delimiters](https://github.com/eBay/jsonpipe#prerequisites).

**Comment by fafhrd91** [comment] 2017-06-03 17:42
I don't really care :)
Using transfer encoding as application protocol just bad.

**Comment by asvetlov** [comment] 2017-06-03 18:34
@pkch "Invalid" label added
