### ISSUE TITLE
Error with access logging and unix socket

### ISSUE THREAD

**Issue by gleb-chipiga** [aio-libs/aiohttp#1091] opened 2016-08-16 11:15 UTC
I run the server on unix socket with asyncio 0.22.5, python 3.5.2 and get the following error:

```
aiohttp.access ERROR 2016-08-16 13:46:34,653: Error in logging
Traceback (most recent call last):
  File "/var/www/polygon_venv/lib/python3.5/site-packages/aiohttp/helpers.py", line 405, in log
    [message, environ, response, transport, time]))
  File "/var/www/polygon_venv/lib/python3.5/site-packages/aiohttp/helpers.py", line 392, in _format_line
    return tuple(m(args) for m in self._methods)
  File "/var/www/polygon_venv/lib/python3.5/site-packages/aiohttp/helpers.py", line 392, in <genexpr>
    return tuple(m(args) for m in self._methods)
  File "/var/www/polygon_venv/lib/python3.5/site-packages/aiohttp/helpers.py", line 348, in _format_a
    return args[3].get_extra_info('peername')[0] if args[3] is not None \
IndexError: index out of range
```

With disabled access log or without unix socket problems not observed.

**Comment by popravich** [comment] 2016-08-16 11:53
Duplicate of #816 (https://github.com/KeepSafe/aiohttp/issues/816#issuecomment-236359667)
fixed in master

**Closed as completed by popravich** 2016-08-16 11:53 UTC
Labels: outdated
