### ISSUE TITLE
Invalid http verbs doesn't drop connection

### ISSUE THREAD

**Issue by cigor** [aio-libs/aiohttp#3212] opened 2018-08-24 07:42 UTC
## Long story short

When using the http_parse C extensions in an aiohttp server some spelling variants of legitimate http verbs hang the event loop

## Expected behaviour

Consistently return a http 400 Bad Request.

## Actual behaviour

Without AIOHTTP_NO_EXTENSIONS=1 some mixed case variants of legitimate http verbs hang the event loop.

## Steps to reproduce

Run the http server example. In another terminal do curl -X PoST http://localhost:8080/ (also works with GeT and several other variations)

The curl hangs. The event loop of the server also hangs until curl is terminated.

Running the server with AIOHTTP_NO_EXTENSIONS=1 does not produce hangs.

## Your environment
This is observed with python3.6 on fedora core 28 with aiohttp 3.3.2

**Comment by webknjaz** [comment] 2018-08-24 08:33
Okay, this needs some debugging.
FTR curl does not normalize or escape stuff, allowing one to send invalid requests.

**Comment by asvetlov** [comment] 2018-08-27 11:29
The loop doesn't hang, it rolls.
The problem is the connection is not dropped even by timeout.
Since http-parser doesn't do it we need to add a timeout for headers reader or something like this.
Pushing aiohttp behind a reverse proxy (nginx, HAProxy etc) eliminates the problem entirely.

**Comment by nicktimko** [comment] 2019-07-03 17:37
I found this on accident...poked at it a bit (https://github.com/nicktimko/aiohttp-badwords) and seemed to come up with that if your HTTP method starts with one of `DEFIJKQVWXYZ` it'll complain back to you and close the connection with the below, otherwise it'll just sit there.  Python 3.7.2/aiohttp 3.5.4

```
Error handling request
Traceback (most recent call last):
  File "/home/nick/.pyenv/versions/global3/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

**Comment by webknjaz** [comment] 2019-07-04 18:44
@nicktimko the code for http-parser is a third-party library. I don't think we can do anything about it.

**Comment by asvetlov** [comment] 2019-09-28 18:01
Sounds like a duplicate of #4109

**Closed as completed by asvetlov** 2019-09-28 18:01 UTC
