### ISSUE TITLE
how to get post data

### ISSUE THREAD

**Issue by reddi-upw** [aio-libs/aiohttp#2566] opened 2017-11-28 11:30 UTC
## Long story short

hi guys,

I need to know how can I get raw form data (body) before making post-request. Is it possible?

Thanks!

**Comment by asvetlov** [comment] 2017-11-28 11:39
Sorry, your question is too broad.

**Comment by reddi-upw** [comment] 2017-11-28 12:10
Sorry, I just mean how can I get prepared request data without doing really request? So I find the method similar to [prepare](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) requests method.

Thanks!

**Comment by asvetlov** [comment] 2017-12-05 08:54
Duplicate of #2516

**Closed as completed by asvetlov** 2017-12-05 08:54 UTC
Labels: question, outdated
