### ISSUE TITLE
Environment dependent error - aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

### ISSUE THREAD

**Issue by leighton** [aio-libs/aiohttp#2954] opened 2018-04-24 14:27 UTC
I've encountered the following error when attempting to get a URL using `aiohttp.ClientSession.get`:
`aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed`

However, the error only occurs in some python environments and not others. Locally I use conda py3.6.4, and it works fine, in production I use a docker alpine image py3.6.4, and I encounter this error.

I've "isolated" the environment difference (line 1 of the Dockerfile) and provided a test case here: https://gist.github.com/leighton/645417b0d8d910cfdb59f7d3be20be99

**Comment by asvetlov** [comment] 2018-04-25 08:41
Everything works fine on my laptop.
Maybe you have network issues.

**Comment by leighton** [comment] 2018-04-25 10:14
Thanks @asvetlov for your quick look into this. I'm very surprised you were not able to reproduce this, did you execute the test using the Dockerfile provided or just the python file? I'm sure there is no network issue as the response headers are parsed, it fails however during the body read.

**Comment by samuelcolvin** [comment] 2018-04-25 10:35
Tried @leighton's example with docker and I get the same result.

All I can say is that I've had big problem's with docker's networking in the past, it does behave weirdly in a few subtle ways and judging from their issue tracker they don't have enough time/energy to investigate these problems.

The script works fine without docker.

**Comment by asvetlov** [comment] 2018-04-25 10:48
I did use `Dockerfile` from the link above.
I have no idea what to do with the issue if I cannot reproduce it.
Moreover, aiohttp is docker container neutral. 
People and I use Docker for very many projects without any issue.

If somebody wants to investigate it more -- you are welcome though.
I suggest to wait for, say, two weeks and close the issue if we'll see no progress on it.

**Comment by samuelcolvin** [comment] 2018-04-25 10:51
If I change the Dockerfile to end

```
# CMD python test.py

RUN apk add --no-cache curl
ENTRYPOINT ["/usr/bin/curl"]
```

and request the url with curl I get the output below. The `{ [6 bytes data]` at the beginning of the response body is odd, I haven't seen it before and don't get when running curl without docker, I think that could be the problem.

```
(env) testaio 0  52ms ➤  docker run --rm testaio -v -s --http1.1 "https://libmod.de/beck-von-litwinenko-zu-skripal-ueber-den-politische-umgang-mit-geheimdienstlichen-operationen/"
*   Trying 85.13.147.154...
* TCP_NODELAY set
* Connected to libmod.de (85.13.147.154) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
...
*  SSL certificate verify ok.
> GET /beck-von-litwinenko-zu-skripal-ueber-den-politische-umgang-mit-geheimdienstlichen-operationen/ HTTP/1.1
> Host: libmod.de
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 25 Apr 2018 10:44:02 GMT
< Server: Apache
< Link: <https://libmod.de/wp-json/>; rel="https://api.w.org/"
< Link: <https://wp.me/p9NIu5-75k>; rel=shortlink
< Upgrade: h2,h2c
< Connection: Upgrade
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
< 
{ [6 bytes data]

<!DOCTYPE html>
<!--[if IE 7]>
...
```

**Comment by asvetlov** [comment] 2018-04-25 10:54
FYI I use Ubuntu, maybe this is the difference? I don't know.

**Comment by samuelcolvin** [comment] 2018-04-25 10:59
I'm on ubuntu 18.04 with docker 17.06.2-ce as installed with snap.

**Comment by asvetlov** [comment] 2018-04-25 11:00
Hmm. Don't know.
Anyway, 6 bytes at the beginning looks very strange.

**Comment by asvetlov** [comment] 2018-05-13 09:36
Closing the issue: aiohttp has nothing to do with broken content

**Closed as completed by asvetlov** 2018-05-13 09:36 UTC
Labels: outdated

**Comment by DusanMadar** [comment] 2019-02-03 11:31
I've encountered the same problem.

`Alpine:3.6` based Docker container - `curl` works, `aiohttp` doesn't.
`Ubuntu:18.04` based Docker container - `curl` works, `aiohttp` works.

Based on traceback, `Response payload is not completed` was caused by https://github.com/aio-libs/aiohttp/blob/7a324fd46ff7dc9bb0bb1bc5afb326e04cf7cef0/aiohttp/http_parser.py#L574.

**Comment by asvetlov** [comment] 2019-02-03 19:52
Additional info would help to pin the problem down:
1. What is your aiohttp version?
2. Would you run your code with C Accelerators (default mode)? Your snippet points on the line which should be executed in slow Pure-Python mode only.
3. Just a line which raises an exception is not very informative. Full traceback is better, a reproducible script is awasome.

**Comment by DusanMadar** [comment] 2019-02-03 21:10
1. aiohttp==3.5.4

2. Can you please give/point to an example of how to do that?

3. I just build and run an image based on https://github.com/DusanMadar/ScrapeMeAgain/blob/master/Dockerfile: `docker build . -t scp:latest; docker run --rm -d --name test scp:latest tail -f /dev/null`

then `docker exec -it test /bin/sh` to the container and run the script below with `Python 3.6.5`

```
#test.py
import asyncio

import aiohttp


def setup_aiohttp_client():
    connector = aiohttp.TCPConnector(force_close=True, ssl=False)
    timeout = aiohttp.ClientTimeout(total=10)
    return aiohttp.ClientSession(connector=connector, timeout=timeout)


async def aget(url, client):
    async with client.get(url) as aresp:
        data = await aresp.text()
        print(data)


client = setup_aiohttp_client()
loop = asyncio.get_event_loop()

try:
    url = "https://libmod.de/beck-von-litwinenko-zu-skripal-ueber-den-politische-umgang-mit-geheimdienstlichen-operationen/"
    loop.run_until_complete(aget(url, client))
finally:
    loop.run_until_complete(client.close())
```

Result
```
/ # python3 test.py 
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    loop.run_until_complete(aget(url, client))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 14, in aget
    data = await aresp.text()          
  File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 1005, in text
    await self.read()
  File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 969, in read
    self._body = await self.content.read()
  File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 359, in read
    block = await self.readany()
  File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 381, in readany
    await self._wait('readany')
  File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 297, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```
I've searched the repo for `Response payload is not completed` which led to https://github.com/aio-libs/aiohttp/blob/7a324fd46ff7dc9bb0bb1bc5afb326e04cf7cef0/aiohttp/client_proto.py#L84. There I've put `import traceback; print(traceback.format_exc())` just after `if self._payload is not None:` and the traceback was

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/client_proto.py", line 80, in connection_lost
    uncompleted = self._parser.feed_eof()
  File "/usr/lib/python3.6/site-packages/aiohttp/http_parser.py", line 211, in feed_eof
    self._payload_parser.feed_eof()
  File "/usr/lib/python3.6/site-packages/aiohttp/http_parser.py", line 575, in feed_eof
    "Not enough data for satisfy transfer length header.")
aiohttp.http_exceptions.TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'
```

which points to the line mentioned in my previous comment.

Hope that helps.

**Comment by luvvien** [comment] 2019-03-13 23:27
[response payload is not completed](https://vien.tech/article72)  solved my problem
