### ISSUE TITLE
aiohttp 3.5.1 munges request url

### ISSUE THREAD

**Issue by khazhyk** [aio-libs/aiohttp#3494] opened 2019-01-07 06:53 UTC
## Long story short

`aiohttp.get(url)` modifies `url` to something else, resulting in not being able to fetch that URL

```
import aiohttp
s = aiohttp.ClientSession()
resp = s.get('https://images-ext-2.discordapp.net/external/n945pegasec2-Y2fwHmMso5IqqPmBSKB883Nid5_xMw/%3Fsize%3D1024/https/images.discordapp.net/avatars/86699011792191488/e8b87f5087ab1e4b722dee85f4831204.png')
resp.url # 'https://images-ext-2.discordapp.net/external/n945pegasec2-Y2fwHmMso5IqqPmBSKB883Nid5_xMw/%3Fsize=1024/https/images.discordapp.net/avatars/86699011792191488/e8b87f5087ab1e4b722dee85f4831204.png'
```

## Expected behaviour

It should request the correct url

## Actual behaviour

It requests the wrong url (it seems to improperly convert `%3D` to `=`, which gives a *different* and *incorrect* url)

## Steps to reproduce

```
import aiohttp
s = aiohttp.ClientSession()
resp = s.get('https://images-ext-2.discordapp.net/external/n945pegasec2-Y2fwHmMso5IqqPmBSKB883Nid5_xMw/%3Fsize%3D1024/https/images.discordapp.net/avatars/86699011792191488/e8b87f5087ab1e4b722dee85f4831204.png')
resp.url # 'https://images-ext-2.discordapp.net/external/n945pegasec2-Y2fwHmMso5IqqPmBSKB883Nid5_xMw/%3Fsize=1024/https/images.discordapp.net/avatars/86699011792191488/e8b87f5087ab1e4b722dee85f4831204.png'
```

## Your environment

aiohttp 3.5.1
linux
python 3.6.5

**Comment by kxepal** [comment] 2019-01-07 07:57
This is duplicate of #3424. Solution could be found in the [first comment](https://github.com/aio-libs/aiohttp/issues/3424#issuecomment-443760653).

**Closed as completed by kxepal** 2019-01-07 07:57 UTC
Labels: outdated
