### ISSUE TITLE
client_max_size 

### ISSUE THREAD

**Issue by cole-dda** [aio-libs/aiohttp#4543] opened 2020-01-29 20:05 UTC
## Long story short

web_request.py

<img width="666" alt="screenshot_3109" src="https://user-images.githubusercontent.com/1077830/73392665-345b6300-4315-11ea-8cfa-7d5097920421.png">

<img width="666" alt="screenshot_3110" src="https://user-images.githubusercontent.com/1077830/73392792-74bae100-4315-11ea-85a0-1ea57b62a95d.png">

## Expected behaviour

image1,line 565 , I think use **">"** is better.

image2,line 625, is right.

## Your environment
aiohttp 3.6.2
python 3.6.8
mac

**Comment by webknjaz** [comment] 2020-01-29 21:38
@cole-dda please post code snippets and fill out the issue template.

**Comment by borysvorona** [comment] 2020-03-16 10:24
Duplicate of https://github.com/aio-libs/aiohttp/issues/4558

**Closed as completed by borysvorona** 2020-03-16 10:24 UTC
Labels: duplicate, invalid
