### ISSUE TITLE
Fails `mypy --strict` because of reexports

### ISSUE THREAD

**Issue by AMDmi3** [aio-libs/aiohttp#3868] opened 2019-06-25 21:20 UTC
## Long story short

With python 3.7, fresh mypy 0.711:

```python
import aiohttp
aiohttp.ClientSession
```
```
% mypy --strict test.py
test.py:3: error: Module has no attribute "ClientSession"
```
This happens because `mypy --strict` expects imported stuff reexported as in
```python
from .client import BaseConnector as BaseConnector
```
while `aiohttp/__init.py__` just imports stuff:
```python
from .client import (BaseConnector, ...)
```

Related: python/mypy#7067

## Expected behaviour

Clean `mypy --strict`, as these errors break checking code which uses aiohttp

**Comment by webknjaz** [comment] 2019-06-25 23:56
Feel free to send a PR :)

**Comment by AMDmi3** [comment] 2019-06-26 00:05
Would it be OK stylewise to just convert to a bunch of `from .foo import bar as bar` lines?

**Comment by webknjaz** [comment] 2019-06-26 00:23
That's a question to @asvetlov. I don't mind personally.

**Comment by asvetlov** [comment] 2019-06-26 08:17
> Would it be OK stylewise to just convert to a bunch of from .foo import bar as bar lines?

Yes. Whatever works for you and `isort` tool :)

Please make sure that both `__init__.py` and `web.py` are processed.
`[mypy]` section from `setup.cfg` worth to be upgraded to support the most strict mode.
The problem is that `mypy` doesn't support `strict=true` in config files but requires decomposition of this mode into a bunch of separate flags. `mypy` is expanding, new options are added to the tool but we didn't  change our config file yet.

**Comment by AMDmi3** [comment] 2019-06-27 16:31
Pull requests are ready. I'm not touching other mypy stuff yet as more work is required there, and these changes seem to be sufficient to unbreak consumer code.

**Comment by AMDmi3** [comment] 2019-07-02 21:10
Ping?

**Comment by webknjaz** [comment] 2019-07-02 21:33
I'm deferring the merge to @asvetlov

**Comment by asvetlov** [comment] 2019-07-19 09:11
Fixed by #3872

**Closed as completed by asvetlov** 2019-07-19 09:11 UTC
Labels: good first issue, need pull request

**Comment by webknjaz** [comment] 2019-07-22 12:05
should we also make our CIs use strict mode?

**Comment by asvetlov** [comment] 2019-07-22 12:18
Make sense.
`mypy` changes a set of concrete options implied by `--strict`.
Maybe we have to use `mypy --strict` explicitly instead of a bunch of detailed options in a config file.

**Comment by webknjaz** [comment] 2019-07-22 13:46
I don't know why our CI didn't catch it then

**Comment by AMDmi3** [comment] 2019-07-22 13:56
Mypy version for CI is fixed at rather old `0.670` for aiohttp, while the latest version is `0.720` - that's why many issues are not caught. Bumping it would require fixing a handful of them first (I've tried, should be not too hard for someone more familiar with the code).

Regarding strict mode, it would be nice to enable it too, but note that it can't be set via `setup.cfg` (it's just not supported by mypy), so it's only possible to list all options which `--strict` enables explicitly. Here's what I use in `setup.cfg`:

```
[mypy]
#strict = True  # not supported
warn_unused_configs = True
disallow_subclassing_any = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
implicit_reexport = False
```

I also set `warn_unreachable = True`, it's new in `0.720` and not included into `--strict`, but I find it quite useful for it revealed a bunch of problems in my code. There are some false positives which can be fixed by adding explicit optional types. Example:

```python
foo = None
...
foo = 1
if bar && foo:  # "right hand of && is always false"
   ...  # "dead code"
```

Fixed like this:

```python
foo: Optional[int] = None
...
foo = 1
if bar && foo:
   ...
```

**Comment by webknjaz** [comment] 2019-07-22 15:38
@AMDmi3 I'd be glad to accept a series of PRs gradually fixing those mypy issues along with adding options and modifying `mypy` invocations in the test runner scripts.

**Comment by AMDmi3** [comment] 2019-07-22 16:44
Ok, I'll try to figure something out.

**Comment by AMDmi3** [comment] 2019-07-22 21:14
See #3927
