### ISSUE TITLE
Python executable crashing when aiohttp installed

### ISSUE THREAD

**Issue by hapdotpy** [aio-libs/aiohttp#4450] opened 2019-12-18 12:31 UTC
## Long story short

Hi, I'm working on a project where I use (among other things) aiohttp.
When I run the .py file everything works fine but whenever I compile it to exe using pyinstaller it crashes 'Python.exe stopped working'.

## Expected behaviour
I'm expecting that it should connect and work (the exe) just like the .py file.

## Actual behaviour
What is happening? the exe crashes instantly while the .py file works fine.

## Your environment
Python 3.6.0
aiohttp 3.6.2
socketio 0.2.1
asyncio 3.4.3
Windows 10
aiohttp(client)

## Other
#276 has the same issue but his fix doesn't fix mine.
Yes I did include aiohttp in hiddenimports.
Installed packages:
```
aiodns==2.0.0
aiohttp==3.6.2
altgraph==0.16.1
asn1crypto==0.24.0
async-timeout==3.0.1
asyncio==3.4.3
attrs==19.3.0
beautifulsoup4==4.8.1
brotlipy==0.7.0
bs4==0.0.1
cchardet==2.1.5
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
colorama==0.4.3
cryptography==2.6.1
dnspython==1.16.0
docopt==0.6.2
Flask==1.1.1
Flask-SocketIO==4.2.1
future==0.18.2
idna==2.8
idna-ssl==1.1.0
itsdangerous==1.1.0
Jinja2==2.10.3
Js2Py==0.66
jwcrypto==0.6.0
jwt==0.6.1
lxml==4.4.2
MarkupSafe==1.1.1
multidict==4.7.1
names==0.3.0
netifaces==0.10.6
numpy==1.17.4
pefile==2019.4.18
protobuf==3.8.0rc1
proxy-manager==0.0.6
psutil==5.6.7
pyarmor==5.5.0
pycares==3.1.0
pycparser==2.19
pyi==0.1.0
PyInstaller==3.5
pyjsparser==2.7.1
PyJWT==1.7.1
pymongo==3.10.0
python-axolotl==0.2.2
python-axolotl-curve25519==0.4.1.post2
python-dateutil==2.8.0
python-engineio==3.11.1
python-jwt==3.2.5
python-magic-bin==0.4.14
python-socketio==4.4.0
pytz==2019.3
pywin32==227
pywin32-ctypes==0.2.0
requests==2.22.0
selenium==3.141.0
six==1.12.0
socketio==0.2.1
soupsieve==1.9.5
termcolor==1.1.0
typing==3.7.4.1
typing-extensions==3.7.4.1
tzlocal==2.0.0
ujson==1.35
urllib3==1.25.7
webwhatsapi==2.0.5
Werkzeug==0.16.0
xlrd==1.2.0
yarl==1.4.2```

**Comment by asvetlov** [comment] 2019-12-18 14:56
Thanks for the report.
The issue is a duplicate of https://github.com/aio-libs/multidict/issues/432

**Closed as completed by asvetlov** 2019-12-18 14:56 UTC
