### ISSUE TITLE
graceful shutdown or reload with gunicorn without shutdown connections

### ISSUE THREAD

**Issue by yangbo1024** [aio-libs/aiohttp#2298] opened 2017-09-29 03:36 UTC
How can I do a graceful shutdown or reload via gunicorn when there are pending connections(will be finished a little later), ensure the pending connections be finished, not directly shutdown by aiohttp?

```python
# worker.py::GunicornWebWorker
    @asyncio.coroutine
    def close(self):
        if self.servers:
            servers = self.servers
            self.servers = None

            # stop accepting connections
            for server, handler in servers.items():
                self.log.info("Stopping server: %s, connections: %s",
                              self.pid, len(handler.connections))
                server.close()
                yield from server.wait_closed()

            # send on_shutdown event
            if hasattr(self.wsgi, 'shutdown'):
                yield from self.wsgi.shutdown()

            # stop alive connections
            tasks = [
                handler.shutdown(
                    timeout=self.cfg.graceful_timeout / 100 * 95)
                for handler in servers.values()]
            yield from asyncio.gather(*tasks, loop=self.loop)

            # cleanup application
            if hasattr(self.wsgi, 'cleanup'):
                yield from self.wsgi.cleanup()
```
when handler.connections > 0, i.e.,has pending connections, if the connection was just create, it will be shutdown throw:
    web_server.py::Server::shutdown -> web_protocol::RequestHandler::shutdown
    

```
# web_protocol::RequestHandler::shutdown
    @asyncio.coroutine
    def shutdown(self, timeout=15.0):
        """Worker process is about to exit, we need cleanup everything and
        stop accepting requests. It is especially important for keep-alive
        connections."""
        self._force_close = True
        # ...
```

here, by set self._force_close = True,
in data_received, the request will be ignored.

```
# web_protocol::RequestHandler::data_received
    @asyncio.coroutine
    def data_received(self, data):
        if self._force_close or self._close:
            return
        # ...
```

so, how to do a graceful shutdown or reload (fg, with gunicorn)?
a way of which is adding an on_shutdown handler, if one can check whether there are pending connections, he can wait until all connections finished with some seconds.
is this ok, or another better way?

My test code:

```
# server.py
from aiohttp import web 

async def handle(request):
    text = "Hello"
    return web.Response(text=text)

app = web.Application()
app.router.add_post('/{name:.*}', handle)
```

```
# client.py
import asyncio
import aiohttp
from aiohttp import web 


async def post():
    url = "http://127.0.0.1:8000/test"
    async with aiohttp.ClientSession() as session:
        async with session.post(url, data=b'test') as resp:
            pass


async def run():
    while 1:
        fus = [post() for i in range(20)]
        await asyncio.wait(fus)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(run())
```

```
# gunicorn.conf
bind = '0.0.0.0:8000'
backlog = 2048
workers = 1 
worker_class = 'aiohttp.GunicornWebWorker'
daemon = False
pidfile = 'pid.pid'
errorlog = 'error.log'
```

**Comment by asvetlov** [comment] 2017-10-24 08:27
Gunicorn spawns aiohttp workers, workers keep connections.
It basically means that worker closing terminates all TCP connections to clients.
There is no way to shut down worker with keeping it's connections, at least using gunicorn architecture.

**Comment by hubo1016** [comment] 2018-03-29 03:56
@asvetlov I think he means to wait for the requests to be finished instead of cancelling them. Sometimes it is important for a "soft" restart:

1. The running server stops listening to the socket
2. A new server starts to listen on the port and process new requests
3. The old server waits until all requests are finished (websockets may be cleaned in another way)

In this way there will not be any noticeable effects on the client side.

**Comment by dwc147896325** [comment] 2018-04-03 01:10
> I think he means to wait for the requests to be finished instead of cancelling them. Sometimes it is important for a "soft" restart

sure~~~

**Comment by pfreixes** [comment] 2018-04-03 05:27
If you run Gunicorn on front of Aiohttp you can use `graceful-timeout` [1], it will give you the chance with a time window for drying the connections that are in progress.

Looks like - I didn't know- that if the `graceful-timeout` is enabled, the default signal used to stop the worker is the SIGTERM. So, to avoid the default kill behavior of that signal you must configure that signal to do nothing for your Aiohttp process. Once the graceful-timeout has been reached, and if and only if the worker didn't stop a SIGKILL to ensure the stop of the process will be sent. [2]

So, IMHO the soft restart can be reached without touching the current Aiohttp implementation. But true, that Aiohttp could implement a default stop for drying connections that are in progress.  

[1] http://docs.gunicorn.org/en/stable/settings.html#graceful-timeout
[2] https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L373

**Comment by hubo1016** [comment] 2018-04-03 11:41
@pfreixes SIGKILL is never a "soft" restart. Workers may have clean up tasks, they will never be executed if killed. You need to use user defined signal like SIGUSR2 to notify the start of a graceful shutdown, and SIGTERM if tineout. I believe at least HAProxy supports this.

**Comment by pfreixes** [comment] 2018-04-03 12:05
@hubo1016 Ive never said that. Please read my comment again and take a look to the gunicorn source code. Workers are soft restarted via SIGTERM and once the grace period is expired then the SIGKILL is used

**Comment by pfreixes** [comment] 2018-04-03 15:12
> If you run Gunicorn on front of Aiohttp you can use graceful-timeout [1], it will give you the chance with a time window for drying the connections that are in progress.

By default Aiohttp running as a Gunicorn worker and with the `graceful-timeout` configured it will use the SIGTERM to try to quit the worker with a graceful period, closing first the socket that accepts the new incoming request and then giving the chance to the Aiohttp worker to finish all of the queued requests that are ready to be processed or are being processed.

Maybe I'm wrong, but true that might be a kind of race condition. Once the shutdown of the worker is asked [1] - as was mentioned by @yangbo1024 - the `self._force_close = True` will prevent that data that is still in the TCP buffers would be processed. 

If we can assume that the listen socket is closed and not more accepted connections will come into the system we might yield the loop until we know for sure that there is no more data to be consumed. /cc @asvetlov

**Comment by hubo1016** [comment] 2018-04-04 02:48
@pfreixes so we still need to fix the aiohttp signal handler to make it shutdown gracefully. This is quite reasonable and could be useful in many ways.

**Comment by pfreixes** [comment] 2018-04-04 04:46
@hubo1016 the signals are already handled - in principle - using the right handlers [1]

[1] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/worker.py#L120

**Comment by hubo1016** [comment] 2018-04-04 06:29
@pfreixes currently the handler aborts all the requests

**Comment by pfreixes** [comment] 2018-04-04 06:58
@hubo1016 take into account that the `web_protocol.shutdown` [1] method should be called, allowing the ongoing request to be finished before the worker is shut down. But true that:

1 ) The pipelined requests will be aborted abruptly.
2) The graceful time of the `shutdown` method must be aligned with the Gunicorn one.

If finally only the pipelined requests are affected this would mean that the example presented by @yangbo1024 is caused only because it didn't use the proper Gunicorn configuration.

In any case, I will make some tests ASAP

[1] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py#L144

**Comment by hubo1016** [comment] 2018-04-04 11:37
@pfreixes it is called, the problem is here
https://github.com/aio-libs/aiohttp/blob/6a6ab7d96d97566a7ae41b1ca8eb54f364ce3c4a/aiohttp/web_protocol.py#L165-L167

It cancels the `start()` task which directly calls the request handler, so the handle of the request cannot be finished. I think it can be simply fixed by replace it with a `asyncio.wait_for`

**Comment by pfreixes** [comment] 2018-04-04 11:55
Take a look two lines above.

**Comment by hubo1016** [comment] 2018-04-04 12:05
@pfreixes I read this issue again and find out that I'm misunderstanding. The problem is that a newly created connection got closed too, even without processing the first request. This might violate the RFC. Usually a client correctly handles connection close on a keep-alive connection, but not on a newly created connection.

It might be improved with the following way:

1. Wait for a bit longer (1 second?) to try to retrieve the next request before discarding data
2. Send "Connection: close" on the requests processed after the shutdown
3. Make sure the payload is received correctly before the final time limit - currently the incoming request and payload is also discarded

[3] might have side effects on web sockets so we may have to deal with it differently.

**Comment by hubo1016** [comment] 2018-04-13 00:46
@pfreixes I don't think the problem is the pipelined requests, in fact they are rarely used. The problem is if you are returning "Connection: keep-alive", it means you are welcome to new requests on this connection. You cannot return "Connection: keep-alive" must shutdown the connection immediately after it, it is confusing to the client side. More importantly, you cannot shutdown the connection before the first request is processed, or the client will think this is a server failure, instead of a keep-alive issue.

Detecting pending messages do work most time, but it is not a robust solution. Even if there are no pending messages in the queue, there may be a partially sent request "on the way", and the payload of the last request may not be retrieved completely.

The proposed POC is valueable, but as mentioned above, I suggest adding a "keep-alive controlling" flag, instead of detecting messages:

```python
    async def shutdown(self, timeout=15.0):
        """Worker process is about to exit, we need cleanup everything and
        stop accepting requests. It is especially important for keep-alive
        connections."""
        
        # setting this flag will make the next response to be sent with "Connection: close"
        # and prevent further processing of incoming requests
        # if we want to support more on pipelined requests, we may modify this to a counter
        self._disable_keep_alive = True

        # TODO: if the connection is upgraded to a web-socket, something may be different
        # maybe skip the waiting and directly cancel the handler? Also, `_force_close` should
        # not be set to allow the last ack on the channel.

        if timeout:
            if not self._last_request_done:
                start = self._loop.time()
                self._last_request_done_waiter = self._loop.create_future()
                with suppress(asyncio.TimeoutError):
                    await asyncio.wait_for(self._last_request_done_waiter, timeout=timeout)
                # Later the timeout will used again to wait for the last
                # incomming request. Timeout value needs to be aligned with
                # time already spend.
                timeout = max(0, timeout - (self._loop.time() - start))

        self._force_close = True
```

also, I read https://github.com/aio-libs/aiohttp/issues/2298#issuecomment-379268518, seems you are only testing on a single request with a designed senario - the request is completely sent and waiting for the response. But there may be more possible senarios for testing:

1. the client send a POST request with a payload a bit larger than the request buffer. The client wait for 1s, and then read the payload and response. If the `_force_close` is enabled, the request payload may be lost
2. the client sends a lot of requests on different connections at the same time (we can simply use `ab` or `wrk` to produce this), so there may be connections that are not completely processed on shutting down. When a graceful shutdown is done on gunicorn, there should not be any uncompleted/error requests - they either complete on the old worker, or complete on the new worker

**Comment by pfreixes** [comment] 2018-04-13 05:57
Yes, the keep alive has to be used to warn the client that the connection will be closed. Good point.

Regarding 

> the client send a POST request with a payload a bit larger than the request buffer. The client wait for 1s, and then read the payload and response. If the _force_close is enabled, the request payload may be lost

IMO this is the first situation that really means a bug which is verifiable in the current code of Aiohttp, so needs a fix. We need to upgrade this use case as a BUG, PR are welcomed. /cc @asvetlov 

Regarding

>the client sends a lot of requests on different connections at the same time (we can simply use ab or wrk to produce this), so there may be connections that are not completely processed on shutting down. When a graceful shutdown is done on gunicorn, there should not be any uncompleted/error requests - they either complete on the old worker, or complete on the new worker

IMO we already discussed all of this.

**Comment by Dreamsorcerer** [comment] 2024-08-02 23:45
I believe this is now handled correctly as documented at: https://docs.aiohttp.org/en/stable/web_advanced.html#graceful-shutdown
If someone can retest with gunicorn and verify there are no additional changes needed specifically for gunicorn, that would be great.

**Closed as completed by Dreamsorcerer** 2024-08-02 23:45 UTC
Labels: wontfix
