### ISSUE TITLE
Testing with pytest-aiohttp test_client raises an AssertionError.

### ISSUE THREAD

**Issue by ilex** [aio-libs/aiohttp#1633] opened 2017-02-15 09:56 UTC
## Long story short

Testing with pytest-aiohttp using test_client raises an AssertionError due to ``url`` is BaseURL, but client expects URL (https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L73). Seems that ``BaseTestServer.make_url`` returns ``BaseURL`` not an URL on line https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/test_utils.py#L96 

Seems that the problem is with ``yarl`` introduced ``BaseURL`` and ``aiohttp`` does not expect that in some places.

## Expected behaviour

``BaseTestServer.make_url`` should return ``URL``. Or client should expect ``BaseURL``.

## Actual behaviour

``BaseTestServer.make_url`` returns ``BaseURL``, but client expects ``URL``.

## Steps to reproduce
Example from the docs:
```python
from aiohttp import web

async def hello(request):
    return web.Response(body=b'Hello, world')

def create_app(loop):
    app = web.Application(loop=loop)
    app.router.add_route('GET', '/', hello)
    return app

async def test_hello(test_client):
    client = await test_client(create_app)
    resp = await client.get('/')
    assert resp.status == 200
    text = await resp.text()
    assert 'Hello, world' in text
```

**Comment by paulannetts** [comment] 2017-02-15 10:51
I'm hitting this too - a whole bunch of my aiohttp based tests rely on this TestClient and are now failing with AssertionError in latest aiohttp build public build from PIP install.

Environment:
Ubuntu 16.04, Python 3.5.2 installed from apt-get.

**Comment by paulannetts** [comment] 2017-02-15 12:22
Looks like root cause is the new version of yarl, see #1635. Workaround is to go back to yarl 0.8.1.

**Comment by insideable** [comment] 2017-02-15 12:24
@paulannetts yarl 0.9.3 works fine.

**Comment by fafhrd91** [comment] 2017-02-15 15:11
Should be fixed with yarl 0.9.6

**Closed as completed by fafhrd91** 2017-02-15 15:11 UTC
Labels: outdated

**Comment by morfair** [comment] 2017-08-25 11:30
@ilex 
sorry. how to contact with you about aiohttp_auth_autz?

**Comment by asvetlov** [comment] 2017-08-25 22:17
Is it https://github.com/ilex/aiohttp_auth_autz ?
What is your question?
