### ISSUE TITLE
aiohttp can't send files by POST request correct

### ISSUE THREAD

**Issue by spkps** [aio-libs/aiohttp#161] opened 2014-10-22 15:00 UTC
I've bumped into multiple different issues when tried to send a file to my REST service. I think it'll be better when I just left some code samples instead of detailed description.

In client part I send two different in size files. I send them using different transports to have the possibility to see errorrs. One of transport is requests and the other is asyncio.

```
import asyncio
import aiohttp
import requests
import urllib.request

url = 'http://127.0.0.1:8080/load/image'

empty_pixel_url = 'http://upload.wikimedia.org/wikipedia/commons/c/ce/Transparent.gif'
large_image_url = 'http://upload.wikimedia.org/wikipedia/commons/d/df/Comet-SidingSpring-Passing-PlanetMars-On-20141019-ArtistConcept-20140905.jpg'

pixel = {'image': ('pixel.jpg', urllib.request.urlopen(empty_pixel_url))}
large_image = {'image': urllib.request.urlopen(large_image_url)}


@asyncio.coroutine
def post_coroutine(files):
    r = yield from aiohttp.request('post', url, files=files)
    return (yield from r.text())


def post_asyncio(files):
    """
        POST by asyncio
    """
    loop = asyncio.get_event_loop()
    res = loop.run_until_complete(post_coroutine(files))
    print(res)


def post_requests(files):
    """
        POST by requests
    """
    response = requests.post(url, files=files)
    print(response.content)


if __name__ == '__main__':

    print('post by requests\n')
    post_requests(pixel)
    post_requests(large_image)

    print('\n'+'-'*20+'\n')
    print('post by asyncio')
    post_asyncio(pixel)
    post_asyncio(large_image)
```

The server part has been written with bottlepy.

```
import time
from pathlib import Path
from bottle import post, run, request

@post('/load/image')
def load_image():
    upload = request.files.get('image')
    fn = upload.filename + str(time.time())
    upload.save(str(Path('/tmp') / fn))
    return dict(filename=fn)

run(host='localhost', port=8080, debug=True)
```

**Comment by fafhrd91** [comment] 2015-03-27 01:32
@kxepal do you think this issue still true with new multipart support?

**Comment by ttezel** [comment] 2015-04-15 18:32
This issue appears invalid now. Reproduced this with:

```
data = FormData()
data.add_field('foobar', open('Transparent.gif', 'rb'), filename='pixeltez.gif')
r = yield from aiohttp.request('post', url, data=data)
return (yield from r.text())
```

And it looks like we generate a valid HTTP request body - on the server side I get:

```
b'--c4a04312312542fc958f61fc4901e41b\r\nCONTENT-TYPE: image/gif\r\nCONTENT-DISPOSITION: form-data; filename="pixeltez.gif"; filename*=utf-8\'\'pixeltez.gif; name=foobar\r\n\r\nGIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x01D\x00;\r\n--c4a04312312542fc958f61fc4901e41b--\r\n'
```

**Comment by asvetlov** [comment] 2015-04-15 18:37
Ok, thanks.
I'll close the issue, feel free to file new one if the problem is still present.

**Closed as completed by asvetlov** 2015-04-15 18:37 UTC
Labels: bug, outdated
