### ISSUE TITLE
add_static breaks normalize_path_middleware

### ISSUE THREAD

**Issue by GeorgeTG** [aio-libs/aiohttp#3086] opened 2018-06-18 08:34 UTC
## Long story short

If the root router has an add_static on '/', normalize_path_middleware won't work.

## Expected behaviour

A slash to be appended at the end of the url

## Actual behaviour

Route `/example` returns 404 when `/example/` is registered.
in `normalize_path_middleware` at the definition of `impl` coroutine theres this check:
`if isinstance(request.match_info.route, SystemRoute):`
Normally `request.match_info.route` is a `<SystemRoute: 404>`
With add_static it becomes `<class 'aiohttp.web_urldispatcher.ResourceRoute'>`
So the middleware ignores it.

## Steps to reproduce
Setup routes like so:
```
def setup_routes(app):
    app.router.add_get('/example/', example_route, name="example")
    app.router.add_static('/', my_path)
```
And of course enable `normalize_path_middleware`
Try to get `/examples`

## Your environment
aiohttp 3.0.4 - Server
python 3.6
archlinux @ latest

**Comment by asvetlov** [comment] 2018-06-18 09:45
The problem is in your code, not in `add_static` or `normalize_path_middleware`.
The middleware is applied if path is not resolved without slash normalization.
Registering a wildcard static route for root path consmes all possible paths.
Thus, middleware is never processed: all possible paths are going to the static handler.

**Closed as completed by asvetlov** 2018-06-18 09:45 UTC
Labels: invalid, outdated
