### ISSUE TITLE
ClientSession.close() is a coroutine warning

### ISSUE THREAD

**Issue by iselind** [aio-libs/aiohttp#2209] opened 2017-08-16 08:49 UTC
## Long story short

I get a deprecation warning in aiohttp 2.2.5 which mess up Vim's quickfix window

## Expected behaviour

No deprecation warning

## Actual behaviour

The code seems to work but i get this deprecation warning each time i run my tests.
```
/usr/local/opt/Python-3.5.2/lib/python3.5/site-packages/aiohttp/helpers.py:139: DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)
```
My tests are based on the unittest package from Python stdlib.

## Steps to reproduce

I run tests using AioHTTPTestCase and unittest_run_loop from aiohttp.test_utils

I don't have any line that close any session in my tests so i guess that the warning comes from the aiohttp library.

## Your environment

```bash
% pip3 freeze | grep aio                
aio-pika==0.18.0
aiodns==1.1.1
aiohttp==2.2.5
```
I'm running Python 3.5.2 using async and await syntax.

**Comment by asvetlov** [comment] 2017-08-17 18:44
Thus you need add lines for explicit session closing maybe?

**Comment by iselind** [comment] 2017-08-18 10:07
that's just it, i don't have any client session code to close. At least not
that I know of.

Patrik

Den 17 aug 2017 20:44 skrev "Andrew Svetlov" <notifications@github.com>:

**Comment by asvetlov** [comment] 2017-08-18 12:30
Do you use plain `aiohttp.request()`?

**Comment by iselind** [comment] 2017-08-18 12:40
My tests look more like this as an example
```python
        request = await self.client.request("GET", "/api/v1/targets")          
        self.assertEqual(request.status, 200)                                  
        text = await request.text()                                            
        self.assertEqual("[]", text)
```
I guess that self.client.request could be a aiohttp.request under the hood. Attaching part of my code base to hopefully clarify what i'm doing in [test.zip](https://github.com/aio-libs/aiohttp/files/1234418/test.zip)

Searching through my code base for the string session, disregarding case, comes up with nothing.

**Comment by iselind** [comment] 2017-08-18 12:41
I can see if i can scale down the code enough to get the issue unless you beat me to it.

**Comment by iselind** [comment] 2017-08-18 18:28
Interestingly enough it seems to be enough with the code in the testing documentation to trigger the error. There is no need to satisfy test tests. It just warn immediately. Attaching the code i tried just now.

See [testcode.zip](https://github.com/aio-libs/aiohttp/files/1235292/testcode.zip)

What i get when i run is
```bash
$ python3 -m unittest
/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py:139: DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)
E
======================================================================
ERROR: test_example (test_foo.MyAppTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
[...]
NameError: name 'root' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.043s

FAILED (errors=1)
```
Notice the deprecation warning in the beginning of the output. So i cannot see there is anything weird with what I'm doing.

I seem to get the Deprecation waring because _CoroGuard wasn't awaited upon. This is discovered in _CoroGuard.__del__().

**Comment by iselind** [comment] 2017-09-04 07:13
Do you have any ideas how to fix this?

**Comment by alekseyl1992** [comment] 2017-09-05 16:46
Got same warning.
This seems to be caused by this lines in `AioHTTPTestCase`:
```
    def tearDown(self):
        self.loop.run_until_complete(self.client.close())
        teardown_test_loop(self.loop)
```
After first lines execution I got:
```
DeprecationWarning: ClientSession.close() is a coroutine
  warnings.warn(self._msg, DeprecationWarning)
```

But it seems, something already changed in master branch:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/test_utils.py#L396

haven't tested it yet

**Comment by alekseyl1992** [comment] 2017-09-17 17:50
I found the source of the problem:
https://github.com/aio-libs/aiohttp/blob/2.2/aiohttp/test_utils.py#L334
and it's already fixed in master branch:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/test_utils.py#L323

So a temporary workaround would be:
```
class FixedTestClient(TestClient):
    @asyncio.coroutine
    def close(self):
        if not self._closed:
            for resp in self._responses:
                resp.close()
            for ws in self._websockets:
                yield from ws.close()
            yield from self._session.close()
            yield from self._server.close()
            self._closed = True

class BaseTestCase(AioHTTPTestCase):
    async def _get_client(self, app):
        """Return a TestClient instance."""
        return FixedTestClient(app, loop=self.loop)
```

So I guess we should just wait for a new version release.

**Closed as completed** 2017-09-17 19:04 UTC
Labels: outdated
