### ISSUE TITLE
ImportWarning when importing aiohttp with warnings enabled

### ISSUE THREAD

**Issue by Norrius** [aio-libs/aiohttp#3428] opened 2018-12-05 14:28 UTC
## Long story short

Importing `aiohttp` results in a lot of ImportWarnings.

While cleaning the app from warnings I noticed that a lot of them stem from aiohttp. To my surprise, simply importing the library results in 10 warning. Of these, DeprecationWarnings are addressed in #3275, but I don't see anything about ImportWarnings.

## Expected behaviour

Expected no warnings on library import.

## Actual behaviour

`ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__`

## Steps to reproduce

```
$ python -Wall -c "import aiohttp"
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
project_root/venv/lib/python3.7/site-packages/aiohttp/multipart.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Sequence, deque
project_root/venv/lib/python3.7/site-packages/aiohttp/multipart.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Sequence, deque
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

## Your environment

Linux Mint 18.3, Python 3.7.1, aiohttp 3.4.4.

**Comment by asvetlov** [comment] 2018-12-05 14:50
The problem is fixed on master.
Please wait for a new release

**Comment by Norrius** [comment] 2018-12-05 15:12
Can confirm that latest master works for me. Thank you.

**Closed as completed** 2018-12-05 15:12 UTC
Labels: bug, outdated
