### ISSUE TITLE
python3.11 -m pip install nextcord error

### ISSUE THREAD

**Issue by machinexa2** [aio-libs/aiohttp#6743] opened 2022-05-08 22:06 UTC
### Describe the bug

  error: subprocess-exited-with-error
  
  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/worker.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/typedefs.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_app.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/http_writer.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_urldispatcher.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/cookiejar.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/connector.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/formdata.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_runner.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/locks.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_ws.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/client_proto.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/multipart.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/client_reqrep.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_server.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/tracing.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_routedef.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_log.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/base_protocol.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/client.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/abc.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/payload_streamer.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/client_ws.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/__init__.py -> build  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for frozenlist (pyproject.toml): finished with status 'error'
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'error'
Failed to build aiohttp frozenlist yarl
ttp/http_parser.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/payload.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/http_exceptions.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/resolver.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_request.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_middlewares.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_response.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_fileresponse.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/client_exceptions.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/helpers.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/web_protocol.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/tcp_helpers.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/test_utils.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/http.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/hdrs.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/streams.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/http_websocket.py -> build/lib.linux-x86_64-cpython-311/aiohttp
      running egg_info
      writing aiohttp.egg-info/PKG-INFO
      writing dependency_links to aiohttp.egg-info/dependency_links.txt
      writing requirements to aiohttp.egg-info/requires.txt
      writing top-level names to aiohttp.egg-info/top_level.txt
      reading manifest file 'aiohttp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'aiohttp' anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'aiohttp/*.html'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE.txt'
      writing manifest file 'aiohttp.egg-info/SOURCES.txt'
      copying aiohttp/_cparser.pxd -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_find_header.c -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_find_header.h -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_find_header.pxd -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_headers.pxi -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_helpers.c -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_helpers.pyi -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_helpers.pyx -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_http_parser.c -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_http_parser.pyx -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_http_writer.c -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_http_writer.pyx -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_websocket.c -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/_websocket.pyx -> build/lib.linux-x86_64-cpython-311/aiohttp
      copying aiohttp/py.typed -> build/lib.linux-x86_64-cpython-311/aiohttp
      creating build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-x86_64-cpython-311/aiohttp/.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/aiohttp
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-x86_64-cpython-311/aiohttp/_websocket.o
      aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  error: subprocess-exited-with-error
  
  × Building wheel for frozenlist (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      **********************
      * Accellerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/frozenlist
      copying frozenlist/__init__.py -> build/lib.linux-x86_64-cpython-311/frozenlist
      running egg_info
      writing frozenlist.egg-info/PKG-INFO
      writing dependency_links to frozenlist.egg-info/dependency_links.txt
      writing top-level names to frozenlist.egg-info/top_level.txt
      reading manifest file 'frozenlist.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'frozenlist/*.html'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file 'frozenlist.egg-info/SOURCES.txt'
      copying frozenlist/__init__.pyi -> build/lib.linux-x86_64-cpython-311/frozenlist
      copying frozenlist/_frozenlist.pyx -> build/lib.linux-x86_64-cpython-311/frozenlist
      copying frozenlist/py.typed -> build/lib.linux-x86_64-cpython-311/frozenlist
      running build_ext
      building 'frozenlist._frozenlist' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/frozenlist
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c frozenlist/_frozenlist.c -o build/temp.linux-x86_64-cpython-311/frozenlist/_frozenlist.o
      frozenlist/_frozenlist.c: In function ‘__Pyx_AddTraceback’:
      frozenlist/_frozenlist.c:432:62: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’}
        432 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
            |                                                              ^~
      frozenlist/_frozenlist.c:7127:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
       7127 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frozenlist
  error: subprocess-exited-with-error
  
  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_quoting.py -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_quoting_py.py -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/__init__.py -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_url.py -> build/lib.linux-x86_64-cpython-311/yarl
      running egg_info
      writing yarl.egg-info/PKG-INFO
      writing dependency_links to yarl.egg-info/dependency_links.txt
      writing requirements to yarl.egg-info/requires.txt
      writing top-level names to yarl.egg-info/top_level.txt
      reading manifest file 'yarl.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl/*.html'
      warning: no previously-included files found matching 'yarl/*.so'
      warning: no previously-included files found matching 'yarl/*.pyd'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info/SOURCES.txt'
      copying yarl/__init__.pyi -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_quoting_c.c -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-cpython-311/yarl
      copying yarl/py.typed -> build/lib.linux-x86_64-cpython-311/yarl
      running build_ext
      building 'yarl._quoting_c' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/yarl
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c yarl/_quoting_c.c -o build/temp.linux-x86_64-cpython-311/yarl/_quoting_c.o
      yarl/_quoting_c.c:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
ERROR: Could not build wheels for aiohttp, frozenlist, yarl, which is required to install pyproject.toml-based projects

### To Reproduce

python3.11 -m pip install nextcord

### Expected behavior

install successfully

### Logs/tracebacks

```python-traceback
Collecting nextcord
  Using cached nextcord-2.0.0a10.tar.gz (889 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting aiohttp<4.0.0,>=3.8.0
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp311-cp311-linux_x86_64.whl
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2.tar.gz (168 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.0->nextcord) (21.4.0)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.8.0->nextcord) (3.3)
Using legacy 'setup.py install' for nextcord, since package 'wheel' is not installed.
Building wheels for collected packages: aiohttp, frozenlist, yarl
  Building wheel for aiohttp (pyproject.toml): started
  Building wheel for aiohttp (pyproject.toml): finished with status 'error'
  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for frozenlist (pyproject.toml): finished with status 'error'
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'error'
Failed to build aiohttp frozenlist yarl

Collecting nextcord
  Using cached nextcord-2.0.0a10.tar.gz (889 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting aiohttp<4.0.0,>=3.8.0
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp311-cp311-linux_x86_64.whl
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0.tar.gz (65 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2.tar.gz (168 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.0->nextcord) (21.4.0)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.8.0->nextcord) (3.3)
Using legacy 'setup.py install' for nextcord, since package 'wheel' is not installed.
Building wheels for collected packages: aiohttp, frozenlist, yarl
  Building wheel for aiohttp (pyproject.toml): started
  Building wheel for aiohttp (pyproject.toml): finished with status 'error'
  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for frozenlist (pyproject.toml): finished with status 'error'
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'error'
Failed to build aiohttp frozenlist yarl
```

### Python Version

```console
$ python --version
Python 3.11.0a7+
```

### aiohttp Version

```console
$ python -m pip show aiohttp
# python3.11 -m pip show aiohttp
WARNING: Package(s) not found: aiohttp
not fuond
```

### multidict Version

```console
$ python -m pip show multidict
not found
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

Linux kali-linux 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by machineaaaac** [comment] 2022-05-08 22:11
python3.10 sucessfully works

**Comment by JelleZijlstra** [comment] 2022-05-08 22:13
This is a duplicate of #6600

**Comment by machinexa2** [comment] 2022-05-08 22:13
oh

**Comment by machinexa2** [comment] 2022-05-08 22:14
k @JelleZijlstra ok

**Closed** 2022-05-08 22:57 UTC
Labels: bug
