### ISSUE TITLE
client_max_size  behavior not same

### ISSUE THREAD

**Issue by cole-dda** [aio-libs/aiohttp#4558] opened 2020-02-06 05:31 UTC
web_request.py

<img width="666" alt="screenshot_3109" src="https://user-images.githubusercontent.com/1077830/73392665-345b6300-4315-11ea-8cfa-7d5097920421.png">

<img width="666" alt="screenshot_3110" src="https://user-images.githubusercontent.com/1077830/73392792-74bae100-4315-11ea-85a0-1ea57b62a95d.png">

## Expected behaviour

image1,line 565 , I think use **">"** is better.

image2,line 625, is right.

## Your environment
aiohttp 3.6.2
python 3.6.8
mac

**Comment by webknjaz** [comment] 2020-02-06 23:50
@cole-dda please send a PR with the change.

**Comment by asvetlov** [comment] 2020-10-16 15:14
I believe, the issue is fixed by #4631

**Closed as completed by asvetlov** 2020-10-16 15:14 UTC
Labels: bug, pr-merged
