### ISSUE TITLE
Frequent asyncio delays larger than 100ms

### ISSUE THREAD

**Issue by dimitar-petrov** [aio-libs/aiohttp#3080] opened 2018-06-13 10:35 UTC
## Long story short
I am noticing asyncio event loop delays. And this is the stack trace of the handle when delay is detected:
```
[<FrameSummary file <string>, line 1 in <module>>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/multiprocessing/spawn.py, line 105 in spawn_main>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/multiprocessing/spawn.py, line 118 in _main>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/multiprocessing/process.py, line 258 in _bootstrap>,
 <FrameSummary file /foopath/3.6.3/envs/pyaio/lib/python3.6/site-packages/foo/bar.py, line 249 in run>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/base_events.py, line 454 in run_until_complete>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/base_events.py, line 421 in run_forever>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/base_events.py, line 1418 in _run_once>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/events.py, line 127 in _run>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/selector_events.py, line 731 in _read_ready>,
 <FrameSummary file /foopath/3.6.3/lib/python3.6/asyncio/sslproto.py, line 516 in data_received>,
 <FrameSummary file /foopath/3.6.3/envs/pyaio/lib/python3.6/site-packages/aiohttp/client_proto.py, line 211 in data_received>,
 <FrameSummary file /foopath/3.6.3/envs/pyaio/lib/python3.6/site-packages/aiohttp/streams.py, line 518 in feed_data>,
 <FrameSummary file /foopath/3.6.3/envs/pyaio/lib/python3.6/site-packages/aiohttp/helpers.py, line 745 in set_result>]
Executing <Handle <TaskWakeupMethWrapper object at 0x7f5edf78ca08>(<Future finis...events.py:275>) created at /foopath/3.6.3/envs/pyaio/lib/python3.6/site-packages/aiohttp/helpers.py:745> too
k 0.120 seconds

```

I am not sure if the delay is caused by aiohttp, but have no idea how to detect the exact coroutine that is responsible and I see at the top of the stack trace is:

```
                    def set_result(fut, result):
                        if not fut.done():
745 ->>               fut.set_result(result)
```
  

## Expected behaviour
Release the event loop faster.

## Your environment
Linux 4.16.5-1-ARCH x86_64

I am using aiohttp as both client and server.

**Comment by asvetlov** [comment] 2018-06-13 11:07
`set_result` calls registered callbacks. Maybe one of them does blocking operation or long CPU computation.

**Comment by Tomcat-Engineering** [comment] 2019-05-09 18:01
I am also seeing something like this, when using aiohttp as a client, with the stack trace pointing to the same `set_result` call.  Like the original poster, I'm not sure whether the delay is caused by aiohttp.

As far as I know I'm not registering any callbacks on futures within aiohttp, but I could be doing something else wrong.  My client code basically looks like this:

```
async with session.get(url, params=params) as response:
    response.raise_for_status()
    return await response.json()
```

Is there anything there that could block the event loop and result in the stack trace pointing to `set_result` in aiohttp?

**Comment by asvetlov** [comment] 2019-05-09 22:19
Hmm. 
In theory, aiohttp should not call long blocking functions.
Do you send files over aiohttp?

**Comment by Tomcat-Engineering** [comment] 2019-05-10 07:39
> Do you send files over aiohttp?

No

**Comment by Tomcat-Engineering** [comment] 2019-05-10 08:51
The same client session is sometimes used to POST JSON though:

```
async with session.post(url, json=data) as response:
    response.raise_for_status()
    return
```

The continue-100 handling seems to be the main bit of client-side code that uses the `set_result` helper I think?

**Comment by asvetlov** [comment] 2019-05-10 09:33
*Default* handling `continue-100` is instant.
Encoding relative large JSON into a string can pause a loop. By default aiohttp performs it as synchronous blocking operation.

**Comment by socketpair** [comment] 2019-05-11 07:50
https://github.com/danielyule/naya ?
https://pykler.github.io/yajl-py/
\+ 100500 tons of another streaming json decoders (and encoders)

**Comment by asvetlov** [comment] 2019-05-11 08:35
I don't see anything which is compatible with the standard JSON module

**Comment by Tomcat-Engineering** [comment] 2019-05-11 09:08
The JSON I'm sending is small, so I don't think the encoder is the cause in my particular case.  

When talking to the same server with a different client I sometimes get errors about the TCP connection being unexpectedly closed during the response.  But in aiohttp I assume that delays/dropped connections in the response should only affect the worker thread, not block the main thread?

**Comment by asvetlov** [comment] 2019-05-11 10:21
The conversation becomes pointless.
The main problem: we have no shared code to discuss.

@dimitar-petrov provided a (limited perhaps) stack trace with blame that `set_result()` for a future takes too long.
Taking into account that `set_result()` can call all registered callbacks the real problem is not `set_result()` itself but a callback code.
Using `multiprocesses` is another potential point of confusing.

@Tomcat-Engineering did provide nothing at all except word that he encounted "similar" problem.
Have no idea what is "worker thread" in his context.

**Comment by Tomcat-Engineering** [comment] 2019-05-11 11:10
I agree, there is not enough information to work on, and it isn't clear whether the problem is in aiohttp or elsewhere.  I just posted here in case there was known issue in aiohttp, or a common user mistake, which could have caused my symptoms.  I'll continue debugging my own code to try to figure out what is going on.  Thanks @asvetlov for taking the time to look at this, much appreciated.

PS - by "worker thread" I meant the asyncio ThreadPoolExecutor threads, I was assuming that was what aiohttp uses to do the blocking i/o calls, but maybe that is not the case.

**Comment by asvetlov** [comment] 2019-05-11 14:52
Aiohttp uses ThreadPoolExecutor for DNS resolving only. All other IO should be asynchronous.
Personally I'm not aware about aiohttp delays itself (it is not a guarantee of 100% absence of problems though)

**Comment by rharder** [comment] 2019-06-04 16:57
I'm also getting similar problems with aiohttp appearing to block too long.  Here is some sample code that illustrates.  About one in ten times running this, I'll get a "takes too long" message.

```
import asyncio
import aiohttp

"""
Periodically get this result:
https://google.com session created, s.get(url)... Executing <Handle <TaskWakeupMethWrapper object at 0x0614B090>(<Future finis...events.py:377>) created at C:\Python37-32\lib\asyncio\futures.py:288> took 0.125 seconds
200 r.text()... <!doctype html><html ...
https://news.google.com session created, s.get(url)... 200 r.text()... <!doctype html><html ...
https://stackoverflow.com session created, s.get(url)... 200 r.text()... <!DOCTYPE html> ...
"""


async def run():
    domains = ("google.com", "news.google.com", "stackoverflow.com")
    for d in domains:
        url = f"https://{d}"
        print(url, end=" ", flush=True)
        async with aiohttp.ClientSession(trust_env=True) as s:
            await asyncio.sleep(0.2)  # Arbitrary to help with console output
            print("session created, s.get(url)...", end=" ", flush=True)
            async with s.get(url) as r:
                await asyncio.sleep(0.2)  # Arbitrary to help with console output
                print(r.status, "r.text()...", end=" ", flush=True)
                text = await r.text()
                await asyncio.sleep(0.2)  # Arbitrary to help with console output
                print(text[:20].strip(), "...", flush=True)


loop = asyncio.get_event_loop()
loop.set_debug(True)
loop.run_until_complete(run())
```

Or put another way that highlights I think it's the https that is causing the problem (run it several times):

```
import asyncio
import aiohttp 

async def _run():
    http = "http://captive.apple.com"
    https = "https://www.google.com"

    print("http - No problem:", http)
    async with aiohttp.ClientSession(trust_env=True) as s:
        async with s.head(http) as r:
            pass

    print("https - Problem:", https)
    async with aiohttp.ClientSession(trust_env=True) as s:
        async with s.head(https) as r:
            pass
"""
Resulting output (about half the time) takes too long:

http - No problem: http://captive.apple.com
https - Problem: https://www.google.com
Executing <Handle <TaskWakeupMethWrapper object at 0x065F5910>(<Future finis...events.py:377>) created at C:\Python37-32\lib\asyncio\futures.py:288> took 0.110 seconds
"""

loop = asyncio.get_event_loop()
loop.set_debug(True)
loop.run_until_complete(_run())
```

**Comment by Dreamsorcerer** [comment] 2024-08-06 00:15
The above example still reproduces on current versions, though not that reliably (even with `loop.slow_callback_duration = 0.025`). I sometimes see:
```
Executing <Handle _SelectorSocketTransport._read_ready() created at /usr/lib/python3.10/asyncio/selector_events.py:254> took 0.030 seconds
```
or
```
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:857, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.049 seconds
```
or
```
Executing <Task pending name='Task-2' coro=<TCPConnector._resolve_host_with_throttle() running at /home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py:904> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[shield.<locals>._inner_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:840] created at /usr/lib/python3.10/asyncio/tasks.py:337> took 0.098 seconds
```

It's difficult to understand exactly what part is slow though, I suspect these are caused by things in asyncio.

**Comment by bdraco** [comment] 2024-08-06 00:29
Are you sure the event loop isn't blocked by something else?

We used to see these in Home Assistant until we fixed the I/O that was happening in the event loop.

There are a surprising number of calls that do I/O that frequently get missed.

**Comment by bdraco** [comment] 2024-08-06 00:30
Here is a list of the most common calls that block the event loop that Home Assistant sees in production python code:
https://github.com/home-assistant/core/blob/54f8f24c2ce782a191fb76701493e03df3ec78ab/homeassistant/block_async_io.py#L64

The two most common are `importlib.import_module` and `builtins.open`

**Comment by Dreamsorcerer** [comment] 2024-08-06 00:58
I'm just running the code above. The only code there is creating a session and making a head request.

I think my computer is a little overloaded, so doing another run, I got all this on a single try:
```
http - No problem: http://captive.apple.com
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:857, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.212 seconds
Executing <Task pending name='Task-2' coro=<TCPConnector._resolve_host_with_throttle() running at /home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py:904> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[shield.<locals>._inner_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:840] created at /usr/lib/python3.10/asyncio/tasks.py:337> took 0.363 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.085 seconds
Executing <Task pending name='Task-3' coro=<staggered_race.<locals>.run_one_coro() running at /usr/lib/python3.10/asyncio/staggered.py:107> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(6, handle=<Handle BaseS...events.py:291>)(), Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475] created at /usr/lib/python3.10/asyncio/staggered.py:130> took 0.110 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.027 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.058 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.333 seconds
Executing <Task finished name='Task-6' coro=<ClientRequest.write_bytes() done, defined at /home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py:552> result=None created at /home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py:673> took 0.085 seconds
Executing <Handle _SelectorSocketTransport._read_ready() created at /usr/lib/python3.10/asyncio/selector_events.py:254> took 0.115 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:9> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/tasks.py:665> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.098 seconds
https - Problem: https://www.google.com
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:15> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:857, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.276 seconds
Executing <Task pending name='Task-7' coro=<TCPConnector._resolve_host_with_throttle() running at /home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py:904> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[shield.<locals>._inner_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:840] created at /usr/lib/python3.10/asyncio/tasks.py:337> took 0.053 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:15> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.057 seconds
Executing <Task pending name='Task-8' coro=<staggered_race.<locals>.run_one_coro() running at /usr/lib/python3.10/asyncio/staggered.py:107> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_write_done(6, handle=<Handle BaseS...events.py:291>)(), Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475] created at /usr/lib/python3.10/asyncio/staggered.py:130> took 0.038 seconds
Executing <Handle SSLProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>) created at /usr/lib/python3.10/asyncio/selector_events.py:773> took 0.048 seconds
Executing <Handle _SelectorSocketTransport._read_ready() created at /usr/lib/python3.10/asyncio/selector_events.py:254> took 0.350 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:15> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.173 seconds
```

**Comment by bdraco** [comment] 2024-08-06 01:37
There is probably more, but one thing that sticks out is that initializing the ssl context does blocking I/O

Home Assistant does it at import time to avoid this problem.

https://github.com/home-assistant/core/blob/54f8f24c2ce782a191fb76701493e03df3ec78ab/homeassistant/util/ssl.py#L116

**Comment by bdraco** [comment] 2024-08-06 12:24
Ideally we would create it in the executor the first time. If thats not possible than at import time is definitely better than doing any blocking I/O in the loop.  The downside is that it might get created and never used if we use the constant approach.

**Comment by Dreamsorcerer** [comment] 2024-08-06 12:35
> Ideally we would create it in the executor the first time.

That should be possible..

**Comment by bdraco** [comment] 2024-08-08 23:52
Adding the milestone since it would be nice to fix soon.  However I'll punt it if we run out of time.

**Comment by bdraco** [comment] 2024-08-10 15:02
https://github.com/aio-libs/aiohttp/pull/8672 is merged. This should help this case. I'm not sure if there are other places blocking I/O is happening though.

**Comment by Dreamsorcerer** [comment] 2024-08-10 20:21
If I'm really stingy on the timeout then I see a couple like this:
```
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:864, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.016 seconds
Executing <Handle cancelled DNSResolver._handle_event(6, 1) created at /usr/lib/python3.10/asyncio/selector_events.py:254> took 0.010 seconds
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:10> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.018 seconds
https - Problem: https://www.google.com
Executing <Task pending name='Task-1' coro=<_run() running at /home/ubuntu/desktop/test.py:15> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.10/asyncio/futures.py:385, Task.task_wakeup()] created at /usr/lib/python3.10/asyncio/base_events.py:429> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184] created at /usr/lib/python3.10/asyncio/tasks.py:636> took 0.022 seconds
Executing <Handle _SelectorSocketTransport._read_ready() created at /usr/lib/python3.10/asyncio/selector_events.py:254> took 0.024 seconds
```

But, I'm not sure what those refer to and they're also well under 100ms. As the original issue seemed focused on HTTPS, I suspect that this can be marked as resolved, unless you have any ideas on the above ones.

**Closed as completed by Dreamsorcerer** 2024-08-10 20:21 UTC
