### ISSUE TITLE
Server keep_alive is too aggressive

### ISSUE THREAD

**Issue by alexmac** [aio-libs/aiohttp#2682] opened 2018-01-22 22:16 UTC
## Long story short

We run an aiohttp server behind an ALB, the ALB maintains a keep-alive connection between the ALB and the backend, the current implementation of the server side keep-alive timeout in aiohttp triggers unexpected connection closes that propagate out to the clients.

## Expected behaviour

The server should allow the client (the ALB in this case) a chance to close the connection by responding with the appropriate `keep-alive:close` header i.e. after the timeout hits I would expect that instead of calling `self.force_close` the force_close flag gets set so that the next response can respond with the close header - triggering the force close on the second run of the timer seems reasonable, but as designed on a  busy service behind a load balancer this is implementation will just randomly terminate valid connections every 75 seconds if they're unlucky enough.

## Actual behaviour

The `RequestHandler` registers a timer that runs every 75 seconds, if it see no active use of the connection it disconnects the underlying connection, but this exposes a race condition where the client has already started making a request and will now recieve a `aiohttp.client_exceptions.ClientConnectorError`

## Steps to reproduce

Run a trivial aiohttp service, for quicker repro modify the default value of `keepalive_timeout` on the RequestHandler to one second, then run a simple script that tries to re-use a connection making requests that are likely to coincide with the timeout value:

```
async def test_client():
	session = aiohttp.ClientSession()
	while True:
		async with session.get('https://localhost.fbn.org/foo') as r:
			result = await r.text()
			print(result)
		await asyncio.sleep(random.uniform(0.99, 1.01))
```

## Your environment

aiohttp 2.1.0, but the implementation of `process_keepalive` in 2.3.9 still calls `force_close`

**Comment by asvetlov** [comment] 2018-01-22 22:22
What is ALB?
Google suggests it is *Amazing Levitating Boulder* but I suspect you did mean something different.

**Comment by alexmac** [comment] 2018-01-22 22:24
Amazon's http load balancer (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html)

**Comment by asvetlov** [comment] 2018-01-22 22:36
Ok, it is ELB actually.

`Keep-Alive` header is non-standard, the standard should use `Connection: close` and assume keep-alive by default.

After keepalive timeout expiring server has nothing to do but close the socket.
The server cannot send HTTP response immediately on expiring: HTTP protocol requests HTTP request from client first.
Server cannot postpone connection closing too: client may never send a request, the server leaks opened socket in this case.
What can you do is increasing keepalive timeout in aiohttp.

I pretty sure every HTTP server (NGINX, Apache, HAProxy) has the same behavior.

**Comment by alexmac** [comment] 2018-01-22 23:28
ELB is their old tcp balancer, ALB is the new http load balancer

Here's a scenario to make this clearer:

We have a simple server running behind the load balancer, the keep_alive timeout is set to the default 75s, a client sends an http request to the load balancer every second, the load balancer is trying to improve performance by maintaining a long-lived connection to the backend using the keep-alive/connection header.

The connection is never idle for more than a second, and yet once every 75s our aiohttp server will decide to hard reset the connection even if the client is in the process of using it. This guarantees that clients will see flaky behavior from the server.

A better implementation would perhaps also include a max number of requests to handle, at which point the final request could send back the appropriate header which would cause the load balancer to perform a clean disconnect/reconnect without the client being impacted.

**Comment by asvetlov** [comment] 2018-01-23 09:18
> ELB is their old tcp balancer, ALB is the new http load balancer

Good to know, thanks.

Hmm, keep alive timeout should be counted from last connection usage (roughly last incoming request time). If aiohttp has different behavior -- it is a bug, should be fixed.

Tests are required.

@alexmac would you work on patch?

**Comment by asvetlov** [comment] 2018-02-01 15:59
Hmm, I cannot reproduce.
aiohttp server shifts keepalive closing time on every incoming request.

My test server and client are here: https://gist.github.com/asvetlov/0a4e4c40bca14ff797f6e27cfef4220c

Explanation of my understanding:

If timeout is expired the connection is ultimately closed, and this is perfectly fine: the connection is in idle state, no response to send connection closing flag.
Waiting for a new incoming request after keepalive timeout expiration violates the whole keepalive idea: disconnection may appear much later or not appear at all.

**Closed as completed** 2018-02-18 17:39 UTC
Labels: invalid, outdated
